// Curated educational resources from trusted sources for Pany Kids Studio.
// Hand-selected by Bố Bình + Claude. Refreshed monthly via /api/refresh-content (Vercel Cron).
//
// Sources prioritized for: pedagogical quality, age-appropriateness, free access, bilingual or VN-friendly.

export type Resource = {
  id: string;
  title_vi: string;
  title_en: string;
  source: string;
  url: string;
  type: 'video' | 'article' | 'tool' | 'game' | 'book' | 'course' | 'channel';
  pillar: 'tech' | 'english' | 'finance' | 'thinking' | 'business' | 'life';
  age_min: number;
  age_max: number;
  duration_min?: number;
  why_vi: string;
  why_en: string;
  prompt_vi?: string;
  prompt_en?: string;
  last_updated: string; // ISO date
};

export const LAST_REFRESHED = '2026-04-30';

export const CURATED_RESOURCES: Resource[] = [
  // ============ TECH (12) ============
  {
    id: 'tech-scratch',
    title_vi: 'Scratch — Lập trình kéo thả',
    title_en: 'Scratch — Drag-drop coding',
    source: 'MIT Media Lab',
    url: 'https://scratch.mit.edu',
    type: 'tool',
    pillar: 'tech',
    age_min: 6,
    age_max: 14,
    why_vi: 'Tool lập trình kéo thả #1 thế giới cho trẻ em. Free, không cần đăng ký, có cộng đồng triệu user.',
    why_en: 'World #1 drag-drop coding tool for kids. Free, no signup, millions of community projects.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-codeorg-hourofcode',
    title_vi: 'Code.org — Hour of Code',
    title_en: 'Code.org — Hour of Code',
    source: 'Code.org',
    url: 'https://code.org/learn',
    type: 'course',
    pillar: 'tech',
    age_min: 6,
    age_max: 16,
    duration_min: 60,
    why_vi: 'Bài học code 1 giờ với Minecraft, Frozen, Star Wars themes. Đã có 1 tỷ lượt học toàn cầu.',
    why_en: 'One-hour coding lessons with Minecraft, Frozen, Star Wars themes. 1 billion+ global completions.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-scratchjr',
    title_vi: 'ScratchJr — Code cho 5-7 tuổi',
    title_en: 'ScratchJr — Coding for ages 5-7',
    source: 'MIT + Tufts',
    url: 'https://www.scratchjr.org',
    type: 'tool',
    pillar: 'tech',
    age_min: 6,
    age_max: 8,
    why_vi: 'Phiên bản Scratch cho trẻ chưa biết đọc. Iconic blocks, tablet-first.',
    why_en: 'Scratch for pre-readers. Iconic blocks, tablet-first.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-app-inventor',
    title_vi: 'MIT App Inventor — Build app Android',
    title_en: 'MIT App Inventor — Build Android apps',
    source: 'MIT',
    url: 'https://appinventor.mit.edu',
    type: 'tool',
    pillar: 'tech',
    age_min: 10,
    age_max: 16,
    why_vi: 'Drag-drop builder cho app Android thật. Cài lên điện thoại bố mẹ được luôn.',
    why_en: 'Drag-drop builder for real Android apps. Installable on parents\' phones.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-khan-cs',
    title_vi: 'Khan Academy — Computer Science',
    title_en: 'Khan Academy — Computer Science',
    source: 'Khan Academy',
    url: 'https://www.khanacademy.org/computing',
    type: 'course',
    pillar: 'tech',
    age_min: 9,
    age_max: 16,
    why_vi: 'Free course từ JS cơ bản đến SQL, animation, web design. Có sub VN cho nhiều bài.',
    why_en: 'Free courses from JS basics to SQL, animation, web design. VN subtitles available.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-freecodecamp',
    title_vi: 'freeCodeCamp — Cert lập trình free',
    title_en: 'freeCodeCamp — Free coding certs',
    source: 'freeCodeCamp.org',
    url: 'https://www.freecodecamp.org',
    type: 'course',
    pillar: 'tech',
    age_min: 12,
    age_max: 16,
    why_vi: '3000+ giờ curriculum từ HTML đến ML. Cert miễn phí, được Microsoft/Spotify công nhận.',
    why_en: '3000+ hours from HTML to ML. Free certs recognized by Microsoft, Spotify.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-cs50',
    title_vi: 'CS50 — Harvard Intro to CS',
    title_en: 'CS50 — Harvard Intro to CS',
    source: 'Harvard',
    url: 'https://cs50.harvard.edu/x',
    type: 'course',
    pillar: 'tech',
    age_min: 13,
    age_max: 16,
    why_vi: 'Course CS huyền thoại của Harvard. Free, có VN sub trên YouTube.',
    why_en: 'Harvard\'s legendary CS intro. Free, VN subs on YouTube.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-replit',
    title_vi: 'Replit — Code online ngay browser',
    title_en: 'Replit — Code online in browser',
    source: 'Replit',
    url: 'https://replit.com',
    type: 'tool',
    pillar: 'tech',
    age_min: 9,
    age_max: 16,
    why_vi: '50+ ngôn ngữ chạy ngay browser. Không cần cài đặt. Có AI assistant.',
    why_en: '50+ languages run in browser. No install. Has AI assistant.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-github-classroom',
    title_vi: 'GitHub — Save code chuyên nghiệp',
    title_en: 'GitHub — Pro code hosting',
    source: 'GitHub',
    url: 'https://github.com',
    type: 'tool',
    pillar: 'tech',
    age_min: 11,
    age_max: 16,
    why_vi: 'Nơi mọi developer trên thế giới lưu code. Student account miễn phí với nhiều perks.',
    why_en: 'Where every developer hosts code. Free student account with many perks.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-anthropic-cookbook',
    title_vi: 'Anthropic Cookbook — Học AI',
    title_en: 'Anthropic Cookbook — Learn AI',
    source: 'Anthropic',
    url: 'https://github.com/anthropics/anthropic-cookbook',
    type: 'article',
    pillar: 'tech',
    age_min: 13,
    age_max: 16,
    why_vi: 'Recipe nấu AI app. Build chatbot, summarizer, coder agent với Claude API.',
    why_en: 'Recipes for AI apps. Build chatbot, summarizer, coder agent with Claude API.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-microbit',
    title_vi: 'micro:bit — Hardware giáo dục',
    title_en: 'micro:bit — Educational hardware',
    source: 'BBC + Microbit Foundation',
    url: 'https://microbit.org',
    type: 'tool',
    pillar: 'tech',
    age_min: 8,
    age_max: 14,
    why_vi: 'Bo mạch có LED, sensor, button. Code bằng Scratch hoặc Python. ~600k VND.',
    why_en: 'Board with LEDs, sensors, buttons. Code with Scratch or Python. ~$25 USD.',
    last_updated: '2026-04-30',
  },
  {
    id: 'tech-tinkercad',
    title_vi: 'Tinkercad — Design 3D + circuits',
    title_en: 'Tinkercad — 3D design + circuits',
    source: 'Autodesk',
    url: 'https://www.tinkercad.com',
    type: 'tool',
    pillar: 'tech',
    age_min: 8,
    age_max: 16,
    why_vi: 'Free 3D modeling + simulate Arduino circuit. Có thể export STL để in 3D.',
    why_en: 'Free 3D modeling + Arduino simulation. Export STL for 3D printing.',
    last_updated: '2026-04-30',
  },

  // ============ ENGLISH (10) ============
  {
    id: 'eng-bbc-learning',
    title_vi: 'BBC Learning English',
    title_en: 'BBC Learning English',
    source: 'BBC',
    url: 'https://www.bbc.co.uk/learningenglish',
    type: 'channel',
    pillar: 'english',
    age_min: 8,
    age_max: 16,
    why_vi: 'Free podcast, video, story. Accent chuẩn UK. Subtitle có sẵn.',
    why_en: 'Free podcasts, videos, stories. Standard UK accent. Subtitles available.',
    last_updated: '2026-04-30',
  },
  {
    id: 'eng-cambridge',
    title_vi: 'Cambridge English — Practice tests',
    title_en: 'Cambridge English — Practice tests',
    source: 'Cambridge Assessment',
    url: 'https://www.cambridgeenglish.org/learning-english',
    type: 'course',
    pillar: 'english',
    age_min: 9,
    age_max: 16,
    why_vi: 'Practice cho Pre-A1 Starters → C2 Proficiency. Có mock tests miễn phí.',
    why_en: 'Practice for Pre-A1 Starters → C2 Proficiency. Free mock tests.',
    last_updated: '2026-04-30',
  },
  {
    id: 'eng-supersimple',
    title_vi: 'Super Simple Songs',
    title_en: 'Super Simple Songs',
    source: 'Skyship Entertainment',
    url: 'https://supersimple.com',
    type: 'channel',
    pillar: 'english',
    age_min: 6,
    age_max: 9,
    why_vi: 'Bài hát tiếng Anh cho trẻ nhỏ. YouTube channel #1 cho ESL kids.',
    why_en: 'English songs for young kids. #1 YouTube channel for ESL kids.',
    last_updated: '2026-04-30',
  },
  {
    id: 'eng-ted-ed',
    title_vi: 'TED-Ed — Video giáo dục 5-10 phút',
    title_en: 'TED-Ed — 5-10 minute education videos',
    source: 'TED',
    url: 'https://ed.ted.com',
    type: 'channel',
    pillar: 'english',
    age_min: 10,
    age_max: 16,
    duration_min: 7,
    why_vi: 'Video animation đẹp về mọi chủ đề. Có VN sub. Train listening academic.',
    why_en: 'Beautifully animated videos on every topic. VN subs available. Trains academic listening.',
    last_updated: '2026-04-30',
  },
  {
    id: 'eng-storyline',
    title_vi: 'Storyline Online — Người nổi tiếng đọc truyện',
    title_en: 'Storyline Online — Celebrities read stories',
    source: 'SAG-AFTRA Foundation',
    url: 'https://storylineonline.net',
    type: 'video',
    pillar: 'english',
    age_min: 6,
    age_max: 11,
    why_vi: 'Free video diễn viên Hollywood đọc truyện thiếu nhi. Có animation.',
    why_en: 'Free videos of Hollywood actors reading kids\' books. With animation.',
    last_updated: '2026-04-30',
  },
  {
    id: 'eng-duolingo',
    title_vi: 'Duolingo — Game tiếng Anh hằng ngày',
    title_en: 'Duolingo — Daily English game',
    source: 'Duolingo',
    url: 'https://duolingo.com',
    type: 'tool',
    pillar: 'english',
    age_min: 7,
    age_max: 16,
    duration_min: 10,
    why_vi: 'Học 10 phút/ngày, streak system như game. Free tier đủ dùng.',
    why_en: '10 min/day, streak system like a game. Free tier sufficient.',
    last_updated: '2026-04-30',
  },
  {
    id: 'eng-khan-grammar',
    title_vi: 'Khan Academy — Grammar cho trẻ',
    title_en: 'Khan Academy — Kids Grammar',
    source: 'Khan Academy',
    url: 'https://www.khanacademy.org/humanities/grammar',
    type: 'course',
    pillar: 'english',
    age_min: 8,
    age_max: 14,
    why_vi: 'Grammar từ cơ bản đến nâng cao. Có quiz tự chấm.',
    why_en: 'Grammar from basics to advanced. Auto-graded quizzes.',
    last_updated: '2026-04-30',
  },
  {
    id: 'eng-youglish',
    title_vi: 'YouGlish — Nghe người bản xứ phát âm',
    title_en: 'YouGlish — Hear native pronunciation',
    source: 'YouGlish',
    url: 'https://youglish.com',
    type: 'tool',
    pillar: 'english',
    age_min: 11,
    age_max: 16,
    why_vi: 'Gõ 1 từ → tìm khắp YouTube người bản xứ phát âm từ đó. Train pronunciation.',
    why_en: 'Type a word → find native speakers saying it across YouTube. Trains pronunciation.',
    last_updated: '2026-04-30',
  },
  {
    id: 'eng-news-in-levels',
    title_vi: 'News in Levels — Tin tức 3 levels',
    title_en: 'News in Levels — News at 3 levels',
    source: 'News in Levels',
    url: 'https://www.newsinlevels.com',
    type: 'article',
    pillar: 'english',
    age_min: 10,
    age_max: 16,
    why_vi: 'Mỗi tin viết ở 3 levels (easy/medium/hard). Có audio đọc theo. Update hằng ngày.',
    why_en: 'Each story at 3 levels. Includes audio. Daily updates.',
    last_updated: '2026-04-30',
  },
  {
    id: 'eng-elsa-speak',
    title_vi: 'ELSA Speak — AI luyện phát âm',
    title_en: 'ELSA Speak — AI pronunciation coach',
    source: 'ELSA',
    url: 'https://elsaspeak.com',
    type: 'tool',
    pillar: 'english',
    age_min: 9,
    age_max: 16,
    why_vi: 'Vietnamese-built AI coach. Phân tích phát âm theo từng âm vị.',
    why_en: 'Vietnamese-built AI coach. Analyzes pronunciation phoneme-by-phoneme.',
    last_updated: '2026-04-30',
  },

  // ============ FINANCE (8) ============
  {
    id: 'fin-junior-achievement',
    title_vi: 'Junior Achievement — Tài chính cho trẻ',
    title_en: 'Junior Achievement — Kids finance',
    source: 'JA Worldwide',
    url: 'https://www.juniorachievement.org',
    type: 'course',
    pillar: 'finance',
    age_min: 6,
    age_max: 16,
    why_vi: 'Chương trình giáo dục tài chính phi lợi nhuận lớn nhất thế giới. Có VN chapter.',
    why_en: 'Largest non-profit financial education program. VN chapter exists.',
    last_updated: '2026-04-30',
  },
  {
    id: 'fin-money-as-you-grow',
    title_vi: 'Money As You Grow (CFPB)',
    title_en: 'Money As You Grow (CFPB)',
    source: 'US Consumer Financial Protection Bureau',
    url: 'https://www.consumerfinance.gov/consumer-tools/money-as-you-grow',
    type: 'article',
    pillar: 'finance',
    age_min: 6,
    age_max: 16,
    why_vi: 'Roadmap tài chính theo từng độ tuổi từ 3-18. Free, không quảng cáo.',
    why_en: 'Age-by-age financial roadmap from 3-18. Free, no ads.',
    last_updated: '2026-04-30',
  },
  {
    id: 'fin-investopedia',
    title_vi: 'Investopedia — Từ điển tài chính',
    title_en: 'Investopedia — Finance dictionary',
    source: 'Investopedia',
    url: 'https://www.investopedia.com',
    type: 'article',
    pillar: 'finance',
    age_min: 13,
    age_max: 16,
    why_vi: 'Bách khoa toàn thư về đầu tư, kinh tế. Stock simulator $100k giả lập.',
    why_en: 'Encyclopedia of investing, economics. $100k stock simulator.',
    last_updated: '2026-04-30',
  },
  {
    id: 'fin-richdadkids',
    title_vi: 'Rich Dad Poor Dad for Teens',
    title_en: 'Rich Dad Poor Dad for Teens',
    source: 'Robert Kiyosaki',
    url: 'https://www.richdad.com',
    type: 'book',
    pillar: 'finance',
    age_min: 11,
    age_max: 16,
    why_vi: 'Phiên bản tài chính cá nhân cho teen. Đọc cùng bố mỗi tuần 1 chương.',
    why_en: 'Personal finance for teens. Read with parent, 1 chapter/week.',
    last_updated: '2026-04-30',
  },
  {
    id: 'fin-money-smart-kids',
    title_vi: 'FDIC Money Smart for Kids',
    title_en: 'FDIC Money Smart for Kids',
    source: 'FDIC (US)',
    url: 'https://www.fdic.gov/resources/consumers/money-smart',
    type: 'course',
    pillar: 'finance',
    age_min: 6,
    age_max: 12,
    why_vi: 'Government-backed curriculum. Free PDF teacher guides + activities.',
    why_en: 'Government-backed curriculum. Free PDF teacher guides + activities.',
    last_updated: '2026-04-30',
  },
  {
    id: 'fin-vn-vietcombank-junior',
    title_vi: 'Vietcombank Junior — Thẻ tiết kiệm cho teen',
    title_en: 'Vietcombank Junior — Teen savings card',
    source: 'Vietcombank',
    url: 'https://www.vietcombank.com.vn',
    type: 'tool',
    pillar: 'finance',
    age_min: 12,
    age_max: 16,
    why_vi: 'Account tiết kiệm cho teen ở Việt Nam. Bố mẹ co-sign, kid quản lý qua app.',
    why_en: 'Teen savings account in Vietnam. Parent co-signs, kid manages via app.',
    last_updated: '2026-04-30',
  },
  {
    id: 'fin-compound-calc',
    title_vi: 'Calculator lãi kép',
    title_en: 'Compound interest calculator',
    source: 'Investor.gov (SEC)',
    url: 'https://www.investor.gov/financial-tools-calculators/calculators/compound-interest-calculator',
    type: 'tool',
    pillar: 'finance',
    age_min: 11,
    age_max: 16,
    why_vi: 'Game thử: 1tr/tháng × 30 năm @ 7% = bao nhiêu? Mind-blowing cho teen.',
    why_en: 'Game: $1k/month × 30 years @ 7% = how much? Mind-blowing for teens.',
    last_updated: '2026-04-30',
  },
  {
    id: 'fin-warren-buffett-letters',
    title_vi: 'Thư cổ đông Warren Buffett',
    title_en: 'Warren Buffett Shareholder Letters',
    source: 'Berkshire Hathaway',
    url: 'https://www.berkshirehathaway.com/letters/letters.html',
    type: 'article',
    pillar: 'finance',
    age_min: 14,
    age_max: 16,
    why_vi: '60 năm thư đầu tư của nhà đầu tư vĩ đại nhất. Đọc 1 thư/tháng cùng bố.',
    why_en: '60 years of letters from the greatest investor. Read 1/month with parent.',
    last_updated: '2026-04-30',
  },

  // ============ THINKING (10) ============
  {
    id: 'think-ted-ed-channel',
    title_vi: 'TED-Ed — Câu hỏi suy nghĩ',
    title_en: 'TED-Ed — Thought-provoking questions',
    source: 'TED',
    url: 'https://www.youtube.com/@TEDEd',
    type: 'channel',
    pillar: 'thinking',
    age_min: 9,
    age_max: 16,
    duration_min: 6,
    why_vi: 'Animation 5-10p với câu hỏi sâu: "If you could change anything in history?"',
    why_en: '5-10min animations with deep questions: "If you could change anything in history?"',
    prompt_vi: 'Sau khi xem, viết 100 từ trả lời câu hỏi của video.',
    prompt_en: 'After watching, write 100 words answering the video\'s question.',
    last_updated: '2026-04-30',
  },
  {
    id: 'think-crashcourse',
    title_vi: 'Crash Course — YouTube giáo dục',
    title_en: 'Crash Course — Educational YouTube',
    source: 'Complexly',
    url: 'https://www.youtube.com/@crashcourse',
    type: 'channel',
    pillar: 'thinking',
    age_min: 11,
    age_max: 16,
    duration_min: 12,
    why_vi: 'Series về World History, Philosophy, Psychology, Computer Science. 15M subs.',
    why_en: 'Series on World History, Philosophy, Psychology, Computer Science. 15M subs.',
    prompt_vi: 'Chọn 1 sự kiện và viết 3 cách khác có thể đã xảy ra.',
    prompt_en: 'Pick one event and write 3 ways it could have gone differently.',
    last_updated: '2026-04-30',
  },
  {
    id: 'think-natgeo-kids',
    title_vi: 'National Geographic Kids',
    title_en: 'National Geographic Kids',
    source: 'NatGeo',
    url: 'https://kids.nationalgeographic.com',
    type: 'channel',
    pillar: 'thinking',
    age_min: 6,
    age_max: 14,
    why_vi: 'Bài viết, video, game về thiên nhiên, lịch sử, khoa học. Quality báo chí thật.',
    why_en: 'Articles, videos, games on nature, history, science. Real journalism quality.',
    prompt_vi: 'Đọc 1 bài → kể lại cho gia đình 5 câu trong bữa tối.',
    prompt_en: 'Read one article → tell family 5 sentences at dinner.',
    last_updated: '2026-04-30',
  },
  {
    id: 'think-wikipedia-simple',
    title_vi: 'Simple English Wikipedia',
    title_en: 'Simple English Wikipedia',
    source: 'Wikimedia Foundation',
    url: 'https://simple.wikipedia.org',
    type: 'article',
    pillar: 'thinking',
    age_min: 9,
    age_max: 14,
    why_vi: 'Wikipedia viết bằng tiếng Anh đơn giản hơn, dùng từ vựng cơ bản.',
    why_en: 'Wikipedia in simpler English, using basic vocabulary.',
    prompt_vi: 'Tìm 1 chủ đề em không biết → đọc 5 phút → viết 50 từ tóm tắt.',
    prompt_en: 'Find a topic you don\'t know → read 5 min → write 50-word summary.',
    last_updated: '2026-04-30',
  },
  {
    id: 'think-veritasium',
    title_vi: 'Veritasium — Khoa học sâu',
    title_en: 'Veritasium — Deep science',
    source: 'Derek Muller',
    url: 'https://www.youtube.com/@veritasium',
    type: 'channel',
    pillar: 'thinking',
    age_min: 11,
    age_max: 16,
    duration_min: 15,
    why_vi: 'Video 15-30p về vật lý, toán, khoa học. Phong cách "thí nghiệm rồi mới giải thích".',
    why_en: '15-30min videos on physics, math, science. "Experiment first, explain after" style.',
    prompt_vi: 'Sau khi xem, dự đoán kết quả thí nghiệm trước khi xem video xác nhận.',
    prompt_en: 'After watching, predict experiment outcomes before re-watching for confirmation.',
    last_updated: '2026-04-30',
  },
  {
    id: 'think-3blue1brown',
    title_vi: '3Blue1Brown — Toán đẹp',
    title_en: '3Blue1Brown — Beautiful math',
    source: 'Grant Sanderson',
    url: 'https://www.youtube.com/@3blue1brown',
    type: 'channel',
    pillar: 'thinking',
    age_min: 12,
    age_max: 16,
    why_vi: 'Animation toán cao cấp đẹp như nghệ thuật. Linear algebra, calculus, neural networks.',
    why_en: 'Beautiful animated higher math. Linear algebra, calculus, neural networks.',
    last_updated: '2026-04-30',
  },
  {
    id: 'think-perplexity',
    title_vi: 'Perplexity AI — Search có nguồn',
    title_en: 'Perplexity AI — Search with citations',
    source: 'Perplexity',
    url: 'https://perplexity.ai',
    type: 'tool',
    pillar: 'thinking',
    age_min: 11,
    age_max: 16,
    why_vi: 'AI search engine cite từng câu. Train kid kỹ năng verify nguồn.',
    why_en: 'AI search engine that cites every sentence. Trains source verification.',
    prompt_vi: 'Hỏi 1 fact → so sánh với 2 nguồn khác (Wiki, NatGeo) → có khớp không?',
    prompt_en: 'Ask a fact → compare with 2 other sources (Wiki, NatGeo) → do they match?',
    last_updated: '2026-04-30',
  },
  {
    id: 'think-kurzgesagt',
    title_vi: 'Kurzgesagt — In a Nutshell',
    title_en: 'Kurzgesagt — In a Nutshell',
    source: 'Kurzgesagt',
    url: 'https://www.youtube.com/@kurzgesagt',
    type: 'channel',
    pillar: 'thinking',
    age_min: 11,
    age_max: 16,
    duration_min: 10,
    why_vi: 'Animation về vũ trụ, sinh học, triết học. Quality cao nhất YouTube.',
    why_en: 'Animation on cosmos, biology, philosophy. Highest quality on YouTube.',
    last_updated: '2026-04-30',
  },
  {
    id: 'think-logical-fallacy-poster',
    title_vi: 'Logical Fallacies Poster',
    title_en: 'Logical Fallacies Poster',
    source: 'Your Logical Fallacy Is',
    url: 'https://yourlogicalfallacyis.com',
    type: 'article',
    pillar: 'thinking',
    age_min: 11,
    age_max: 16,
    why_vi: '24 logical fallacies với ví dụ + meme. Print poster treo nhà.',
    why_en: '24 logical fallacies with examples + memes. Print poster for the wall.',
    prompt_vi: 'Mỗi tuần xem 1 fallacy → tìm 1 ví dụ trong quảng cáo TV/social.',
    prompt_en: 'Each week study 1 fallacy → find one example in TV/social ads.',
    last_updated: '2026-04-30',
  },
  {
    id: 'think-brilliant',
    title_vi: 'Brilliant — Toán tương tác',
    title_en: 'Brilliant — Interactive math',
    source: 'Brilliant.org',
    url: 'https://brilliant.org',
    type: 'course',
    pillar: 'thinking',
    age_min: 10,
    age_max: 16,
    why_vi: 'Course tương tác về math, logic, CS. Free tier có nhiều bài.',
    why_en: 'Interactive courses on math, logic, CS. Free tier has many lessons.',
    last_updated: '2026-04-30',
  },

  // ============ BUSINESS (10) ============
  {
    id: 'biz-lemonade-day',
    title_vi: 'Lemonade Day — Vận hành tiệm thật',
    title_en: 'Lemonade Day — Run a real lemonade stand',
    source: 'Lemonade Day Foundation',
    url: 'https://lemonadeday.org',
    type: 'course',
    pillar: 'business',
    age_min: 6,
    age_max: 14,
    why_vi: 'Curriculum 14 bài để vận hành tiệm chanh thật: budget, marketing, profit.',
    why_en: '14-lesson curriculum to run a real lemonade stand: budget, marketing, profit.',
    prompt_vi: 'Mở tiệm bán nước/bánh tại cổng nhà 1 ngày cuối tuần. Tính P&L cuối ngày.',
    prompt_en: 'Run a stand at your gate one weekend day. Calculate P&L at end.',
    last_updated: '2026-04-30',
  },
  {
    id: 'biz-vn-shopee-academy',
    title_vi: 'Shopee University Vietnam',
    title_en: 'Shopee University Vietnam',
    source: 'Shopee',
    url: 'https://uni.shopee.vn',
    type: 'course',
    pillar: 'business',
    age_min: 12,
    age_max: 16,
    why_vi: 'Course free dạy bán hàng online ở VN. Marketing, ship, COD, livestream.',
    why_en: 'Free course on online selling in VN. Marketing, ship, COD, livestream.',
    last_updated: '2026-04-30',
  },
  {
    id: 'biz-yc-startup-school',
    title_vi: 'Y Combinator Startup School',
    title_en: 'Y Combinator Startup School',
    source: 'Y Combinator',
    url: 'https://www.startupschool.org',
    type: 'course',
    pillar: 'business',
    age_min: 14,
    age_max: 16,
    why_vi: 'Course free từ YC — vườn ươm startup top thế giới. Build to MVP.',
    why_en: 'Free course from YC — world\'s top startup incubator. Build to MVP.',
    last_updated: '2026-04-30',
  },
  {
    id: 'biz-vn-case-vinamilk',
    title_vi: 'Case study: Vinamilk thoái vốn nhà nước',
    title_en: 'Case: Vinamilk state divestment',
    source: 'PANY curated',
    url: 'https://en.wikipedia.org/wiki/Vinamilk',
    type: 'article',
    pillar: 'business',
    age_min: 13,
    age_max: 16,
    why_vi: 'Vinamilk = #1 sữa VN. Cách họ scale từ HTX 1976 → tập đoàn $4B.',
    why_en: 'Vinamilk = VN\'s #1 dairy. From cooperative 1976 → $4B corporation.',
    prompt_vi: 'Em sẽ đầu tư vào Vinamilk hay đối thủ TH True Milk? Why?',
    prompt_en: 'Would you invest in Vinamilk or competitor TH True Milk? Why?',
    last_updated: '2026-04-30',
  },
  {
    id: 'biz-vn-case-thegioididong',
    title_vi: 'Case study: Thế Giới Di Động',
    title_en: 'Case: Thế Giới Di Động (Mobile World)',
    source: 'PANY curated',
    url: 'https://www.thegioididong.com',
    type: 'article',
    pillar: 'business',
    age_min: 13,
    age_max: 16,
    why_vi: 'Từ 3 cửa hàng 2004 → 5000+ chuỗi 2025. Bài học về retail expansion.',
    why_en: 'From 3 stores 2004 → 5000+ chain 2025. Lessons in retail expansion.',
    prompt_vi: 'Tại sao TGDD thắng FPT Shop? Phân tích 3 yếu tố.',
    prompt_en: 'Why did TGDD beat FPT Shop? Analyze 3 factors.',
    last_updated: '2026-04-30',
  },
  {
    id: 'biz-vn-case-vinfast',
    title_vi: 'Case study: VinFast IPO Mỹ',
    title_en: 'Case: VinFast US IPO',
    source: 'PANY curated',
    url: 'https://vinfastauto.us',
    type: 'article',
    pillar: 'business',
    age_min: 14,
    age_max: 16,
    why_vi: 'VN ô tô EV niêm yết Nasdaq 2023. Bài học scale toàn cầu + risk.',
    why_en: 'VN EV listed on Nasdaq 2023. Lessons in global scaling + risk.',
    prompt_vi: 'VinFast có nên tiếp tục bán ở Mỹ không? Lý do.',
    prompt_en: 'Should VinFast continue selling in the US? Why?',
    last_updated: '2026-04-30',
  },
  {
    id: 'biz-product-hunt',
    title_vi: 'ProductHunt — Daily startups',
    title_en: 'ProductHunt — Daily startups',
    source: 'ProductHunt',
    url: 'https://producthunt.com',
    type: 'channel',
    pillar: 'business',
    age_min: 12,
    age_max: 16,
    why_vi: 'Mỗi ngày 30+ sản phẩm mới được launch. Học pattern thành công.',
    why_en: '30+ new products launched daily. Learn success patterns.',
    last_updated: '2026-04-30',
  },
  {
    id: 'biz-shark-tank-vn',
    title_vi: 'Shark Tank Việt Nam',
    title_en: 'Shark Tank Vietnam',
    source: 'VTV3 / YouTube',
    url: 'https://www.youtube.com/@SharkTankVietnam',
    type: 'channel',
    pillar: 'business',
    age_min: 11,
    age_max: 16,
    why_vi: 'Pitch thật của startup VN. Học cách present, valuation, negotiation.',
    why_en: 'Real Vietnamese startup pitches. Learn to present, valuation, negotiation.',
    prompt_vi: 'Xem 1 tập → em đầu tư hay không? Defense ý kiến với gia đình.',
    prompt_en: 'Watch 1 episode → would you invest? Defend your view to family.',
    last_updated: '2026-04-30',
  },
  {
    id: 'biz-canva',
    title_vi: 'Canva for Education — Design free',
    title_en: 'Canva for Education — Free design',
    source: 'Canva',
    url: 'https://www.canva.com/education',
    type: 'tool',
    pillar: 'business',
    age_min: 8,
    age_max: 16,
    why_vi: 'Free pro version cho học sinh. Design logo, banner, presentation cho business riêng.',
    why_en: 'Free pro version for students. Design logo, banner, presentation for own business.',
    last_updated: '2026-04-30',
  },
  {
    id: 'biz-stripe-atlas',
    title_vi: 'Stripe Atlas Guide — Bắt đầu công ty',
    title_en: 'Stripe Atlas Guide — Start a company',
    source: 'Stripe',
    url: 'https://stripe.com/atlas/guides',
    type: 'article',
    pillar: 'business',
    age_min: 14,
    age_max: 16,
    why_vi: 'Hướng dẫn miễn phí cách bắt đầu startup global từ Stripe (CEO Patrick Collison).',
    why_en: 'Free guide to starting a global startup from Stripe (CEO Patrick Collison).',
    last_updated: '2026-04-30',
  },

  // ============ LIFE (10) ============
  {
    id: 'life-natgeo-explorer',
    title_vi: 'Nat Geo Young Explorers',
    title_en: 'Nat Geo Young Explorers',
    source: 'National Geographic',
    url: 'https://www.nationalgeographic.org/education',
    type: 'course',
    pillar: 'life',
    age_min: 8,
    age_max: 14,
    why_vi: 'Hoạt động khám phá thiên nhiên + grants nhỏ cho dự án trẻ.',
    why_en: 'Nature exploration activities + small grants for kid projects.',
    last_updated: '2026-04-30',
  },
  {
    id: 'life-vn-museum-history',
    title_vi: 'Bảo tàng Lịch sử Quốc gia VN',
    title_en: 'VN National Museum of History',
    source: 'Bảo tàng Lịch sử',
    url: 'https://baotanglichsu.vn',
    type: 'tool',
    pillar: 'life',
    age_min: 6,
    age_max: 16,
    why_vi: '4000 năm lịch sử VN. Tour 3D ảo nếu chưa đi được. Hà Nội.',
    why_en: '4000 years of VN history. Virtual 3D tour available. Hanoi.',
    last_updated: '2026-04-30',
  },
  {
    id: 'life-vn-museum-ethnology',
    title_vi: 'Bảo tàng Dân tộc học VN',
    title_en: 'VN Museum of Ethnology',
    source: 'VME',
    url: 'http://www.vme.org.vn',
    type: 'tool',
    pillar: 'life',
    age_min: 7,
    age_max: 16,
    why_vi: '54 dân tộc VN. Outdoor exhibit có nhà sàn thật. Top 25 bảo tàng châu Á.',
    why_en: '54 VN ethnic groups. Outdoor exhibit with real stilt houses. Top 25 in Asia.',
    last_updated: '2026-04-30',
  },
  {
    id: 'life-google-arts',
    title_vi: 'Google Arts & Culture',
    title_en: 'Google Arts & Culture',
    source: 'Google',
    url: 'https://artsandculture.google.com',
    type: 'tool',
    pillar: 'life',
    age_min: 7,
    age_max: 16,
    why_vi: 'Tour ảo 2000+ bảo tàng toàn thế giới. Louvre, Smithsonian, museums VN.',
    why_en: 'Virtual tours of 2000+ museums worldwide. Louvre, Smithsonian, VN museums.',
    last_updated: '2026-04-30',
  },
  {
    id: 'life-iss-livestream',
    title_vi: 'NASA ISS Live Stream',
    title_en: 'NASA ISS Live Stream',
    source: 'NASA',
    url: 'https://www.nasa.gov/live',
    type: 'video',
    pillar: 'life',
    age_min: 6,
    age_max: 16,
    why_vi: 'Stream trực tiếp Trạm Vũ trụ Quốc tế. Xem trái đất từ 400km cao.',
    why_en: 'Live stream from International Space Station. See Earth from 400km up.',
    last_updated: '2026-04-30',
  },
  {
    id: 'life-allrecipes',
    title_vi: 'Cookpad VN — Nấu ăn cùng bố mẹ',
    title_en: 'Cooking with parents',
    source: 'Cookpad VN',
    url: 'https://cookpad.com/vn',
    type: 'tool',
    pillar: 'life',
    age_min: 8,
    age_max: 16,
    why_vi: 'Recipes VN có ảnh từng bước. Học toán phân số qua đo lường thật.',
    why_en: 'VN recipes with step photos. Learn fractions via real measurement.',
    last_updated: '2026-04-30',
  },
  {
    id: 'life-iNaturalist',
    title_vi: 'iNaturalist — Identify động thực vật',
    title_en: 'iNaturalist — Identify wildlife',
    source: 'California Academy of Sciences',
    url: 'https://www.inaturalist.org',
    type: 'tool',
    pillar: 'life',
    age_min: 7,
    age_max: 16,
    why_vi: 'Chụp ảnh chim, hoa, côn trùng → AI identify + đóng góp data thật cho nhà khoa học.',
    why_en: 'Photo birds, flowers, insects → AI IDs + contribute real data to scientists.',
    last_updated: '2026-04-30',
  },
  {
    id: 'life-volunteer-vn',
    title_vi: 'Tổ chức tình nguyện VN — TamYeuThuong',
    title_en: 'VN volunteer org — Loving Care',
    source: 'TamYeuThuong.com',
    url: 'https://tamyeuthuong.com',
    type: 'channel',
    pillar: 'life',
    age_min: 12,
    age_max: 16,
    why_vi: 'Network volunteer VN: trại trẻ, viện dưỡng lão, môi trường. Đi cùng bố mẹ.',
    why_en: 'VN volunteer network: orphanages, elderly homes, environment. Go with parents.',
    last_updated: '2026-04-30',
  },
  {
    id: 'life-windy',
    title_vi: 'Windy — Bản đồ thời tiết toàn cầu',
    title_en: 'Windy — Global weather map',
    source: 'Windy.com',
    url: 'https://windy.com',
    type: 'tool',
    pillar: 'life',
    age_min: 8,
    age_max: 16,
    why_vi: 'Visualize gió, mưa, bão thời gian thực. Học khí tượng qua animation.',
    why_en: 'Real-time wind, rain, storm visualization. Learn meteorology via animation.',
    last_updated: '2026-04-30',
  },
  {
    id: 'life-stellarium',
    title_vi: 'Stellarium — Bầu trời sao',
    title_en: 'Stellarium — Star sky',
    source: 'Stellarium',
    url: 'https://stellarium-web.org',
    type: 'tool',
    pillar: 'life',
    age_min: 7,
    age_max: 16,
    why_vi: 'Free planetarium browser. Identify sao, hành tinh, chòm sao đêm nay tại VN.',
    why_en: 'Free in-browser planetarium. Identify stars, planets, constellations tonight in VN.',
    last_updated: '2026-04-30',
  },

  // ============ GAME-BASED LEARNING (5) — added by anh's request 2026-04-30 ============
  {
    id: 'game-quizizz',
    title_vi: 'Quizizz — Quiz tương tác',
    title_en: 'Quizizz — Interactive quizzes',
    source: 'Quizizz',
    url: 'https://quizizz.com',
    type: 'game',
    pillar: 'tech',
    age_min: 7,
    age_max: 16,
    why_vi: 'Quiz game-based dùng cho mọi môn. Tự tạo quiz hoặc chơi quiz cộng đồng.',
    why_en: 'Game-based quizzes for any subject. Create your own or play community quizzes.',
    last_updated: '2026-04-30',
  },
  {
    id: 'game-kahoot',
    title_vi: 'Kahoot! — Quiz cả lớp cùng chơi',
    title_en: 'Kahoot! — Whole-class quiz game',
    source: 'Kahoot!',
    url: 'https://kahoot.com',
    type: 'game',
    pillar: 'tech',
    age_min: 7,
    age_max: 16,
    why_vi: 'Quiz live multiplayer. Cả gia đình thi đua trên màn hình lớn vào bữa tối.',
    why_en: 'Live multiplayer quiz. Whole family competes on big screen at dinner.',
    last_updated: '2026-04-30',
  },
  {
    id: 'game-educaplay',
    title_vi: 'Educaplay — 17 loại game học tập',
    title_en: 'Educaplay — 17 types of learning games',
    source: 'Educaplay',
    url: 'https://www.educaplay.com',
    type: 'game',
    pillar: 'english',
    age_min: 6,
    age_max: 14,
    why_vi: 'Crossword, ghép cặp, điền chữ, audio game. Free, đa ngôn ngữ.',
    why_en: 'Crosswords, matching, fill-in, audio games. Free, multilingual.',
    last_updated: '2026-04-30',
  },
  {
    id: 'game-baamboozle',
    title_vi: 'Baamboozle — Game ESL cho lớp học',
    title_en: 'Baamboozle — ESL classroom game',
    source: 'Baamboozle',
    url: 'https://www.baamboozle.com',
    type: 'game',
    pillar: 'english',
    age_min: 6,
    age_max: 14,
    why_vi: 'Game tiếng Anh team-based. Hàng ngàn template free.',
    why_en: 'Team-based English games. Thousands of free templates.',
    last_updated: '2026-04-30',
  },
  {
    id: 'game-wordwall',
    title_vi: 'Wordwall — Tạo game tương tác nhanh',
    title_en: 'Wordwall — Quick interactive games',
    source: 'Wordwall',
    url: 'https://wordwall.net',
    type: 'game',
    pillar: 'english',
    age_min: 6,
    age_max: 14,
    why_vi: 'Tạo game học tập trong 1 phút: match-up, quiz, vòng quay, anagram.',
    why_en: 'Create learning games in 1 min: match-up, quiz, spin wheel, anagram.',
    last_updated: '2026-04-30',
  },

  // ============ RESEARCH DATABASES (16) — for teen 13+ academic exploration ============
  {
    id: 'research-arxiv',
    title_vi: 'arXiv — Preprint khoa học',
    title_en: 'arXiv — Science preprints',
    source: 'Cornell University',
    url: 'https://arxiv.org',
    type: 'article',
    pillar: 'thinking',
    age_min: 14,
    age_max: 16,
    why_vi: 'Nơi mọi paper vật lý, toán, CS được công bố trước peer-review. AI papers ở đây.',
    why_en: 'Where every physics, math, CS paper is published pre-peer-review. AI papers live here.',
    prompt_vi: 'Tìm 1 paper AI mới → đọc abstract → giải thích cho gia đình bằng 5 câu.',
    prompt_en: 'Find a new AI paper → read abstract → explain to family in 5 sentences.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-pubmed',
    title_vi: 'PubMed Central — Nghiên cứu y học',
    title_en: 'PubMed Central — Medical research',
    source: 'NIH (US)',
    url: 'https://www.ncbi.nlm.nih.gov/pmc',
    type: 'article',
    pillar: 'thinking',
    age_min: 14,
    age_max: 16,
    why_vi: '8M+ paper y học miễn phí. Học cách verify thông tin sức khoẻ thay vì TikTok.',
    why_en: '8M+ free medical papers. Learn to verify health info instead of TikTok.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-biorxiv',
    title_vi: 'bioRxiv — Sinh học preprints',
    title_en: 'bioRxiv — Biology preprints',
    source: 'Cold Spring Harbor Lab',
    url: 'https://www.biorxiv.org',
    type: 'article',
    pillar: 'thinking',
    age_min: 14,
    age_max: 16,
    why_vi: 'Preprint sinh học trước peer-review. Nguồn paper Covid được dùng nhiều nhất 2020.',
    why_en: 'Pre-peer-review biology preprints. Most-used Covid paper source in 2020.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-plos',
    title_vi: 'PLOS — Open access khoa học',
    title_en: 'PLOS — Open access science',
    source: 'Public Library of Science',
    url: 'https://plos.org',
    type: 'article',
    pillar: 'thinking',
    age_min: 13,
    age_max: 16,
    why_vi: 'Pioneer phong trào open access. Tất cả paper miễn phí, peer-reviewed.',
    why_en: 'Open access pioneer. All papers free + peer-reviewed.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-semanticscholar',
    title_vi: 'Semantic Scholar — AI search papers',
    title_en: 'Semantic Scholar — AI paper search',
    source: 'Allen Institute for AI',
    url: 'https://www.semanticscholar.org',
    type: 'tool',
    pillar: 'thinking',
    age_min: 13,
    age_max: 16,
    why_vi: '200M papers + AI tóm tắt + citation graph. Khám phá research connection.',
    why_en: '200M papers + AI summaries + citation graph. Explore research connections.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-core',
    title_vi: 'CORE — 200M papers open',
    title_en: 'CORE — 200M open papers',
    source: 'Open University UK',
    url: 'https://core.ac.uk',
    type: 'tool',
    pillar: 'thinking',
    age_min: 13,
    age_max: 16,
    why_vi: 'Aggregator lớn nhất world cho academic open access papers.',
    why_en: 'World\'s largest aggregator for open access academic papers.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-openaire',
    title_vi: 'OpenAIRE — EU research network',
    title_en: 'OpenAIRE — EU research network',
    source: 'European Commission',
    url: 'https://www.openaire.eu',
    type: 'tool',
    pillar: 'thinking',
    age_min: 14,
    age_max: 16,
    why_vi: 'Hệ thống research công khai EU funded. Papers, dữ liệu, software.',
    why_en: 'EU-funded open research system. Papers, datasets, software.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-osf',
    title_vi: 'OSF Preprints — Multi-discipline',
    title_en: 'OSF Preprints — Multi-discipline',
    source: 'Center for Open Science',
    url: 'https://osf.io/preprints',
    type: 'article',
    pillar: 'thinking',
    age_min: 13,
    age_max: 16,
    why_vi: 'Preprint mọi ngành: psychology, education, social sci. Replication-friendly.',
    why_en: 'Preprints in every field: psychology, education, social sci. Replication-friendly.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-zenodo',
    title_vi: 'Zenodo — Research data + code',
    title_en: 'Zenodo — Research data + code',
    source: 'CERN',
    url: 'https://zenodo.org',
    type: 'tool',
    pillar: 'thinking',
    age_min: 13,
    age_max: 16,
    why_vi: 'Lưu trữ paper, dataset, code khoa học miễn phí. Citable DOI.',
    why_en: 'Free hosting for papers, datasets, scientific code. Citable DOI.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-eric',
    title_vi: 'ERIC — Education research',
    title_en: 'ERIC — Education research',
    source: 'US Dept of Education',
    url: 'https://eric.ed.gov',
    type: 'article',
    pillar: 'thinking',
    age_min: 13,
    age_max: 16,
    why_vi: '2M+ paper về giáo dục. Hữu ích cho bố hiểu pedagogy + cho teen exploring teaching.',
    why_en: '2M+ education papers. Useful for parents understanding pedagogy + teens exploring teaching.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-philpapers',
    title_vi: 'PhilPapers — Triết học',
    title_en: 'PhilPapers — Philosophy',
    source: 'University of Western Ontario',
    url: 'https://philpapers.org',
    type: 'article',
    pillar: 'thinking',
    age_min: 14,
    age_max: 16,
    why_vi: 'Index lớn nhất world của paper triết học. Đọc với Crash Course Philosophy.',
    why_en: 'World\'s largest index of philosophy papers. Pair with Crash Course Philosophy.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-scielo',
    title_vi: 'SciELO — LatAm + Iberian science',
    title_en: 'SciELO — LatAm + Iberian science',
    source: 'SciELO Network',
    url: 'https://scielo.org',
    type: 'tool',
    pillar: 'thinking',
    age_min: 14,
    age_max: 16,
    why_vi: 'Open access papers Mỹ Latinh, Tây Ban Nha, Bồ Đào Nha. Đa dạng hoá nguồn.',
    why_en: 'Open access papers from Latin America, Spain, Portugal. Source diversification.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-mdpi',
    title_vi: 'MDPI — Open access journals',
    title_en: 'MDPI — Open access journals',
    source: 'MDPI',
    url: 'https://www.mdpi.com',
    type: 'article',
    pillar: 'thinking',
    age_min: 13,
    age_max: 16,
    why_vi: '400+ open access journals. Tốc độ publish nhanh nhất ngành.',
    why_en: '400+ open access journals. Fastest publishing in the industry.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-springeropen',
    title_vi: 'SpringerOpen — Quality OA papers',
    title_en: 'SpringerOpen — Quality OA papers',
    source: 'Springer Nature',
    url: 'https://www.springeropen.com',
    type: 'article',
    pillar: 'thinking',
    age_min: 13,
    age_max: 16,
    why_vi: 'Open access wing của Springer. Quality cao, peer-reviewed strict.',
    why_en: 'Open access wing of Springer. High quality, strict peer review.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-nature-comms',
    title_vi: 'Nature Communications — OA Nature',
    title_en: 'Nature Communications — OA Nature',
    source: 'Nature Publishing',
    url: 'https://www.nature.com/ncomms',
    type: 'article',
    pillar: 'thinking',
    age_min: 14,
    age_max: 16,
    why_vi: 'Open access journal của Nature. Top tier research, free đọc.',
    why_en: 'Nature\'s open access journal. Top-tier research, free to read.',
    last_updated: '2026-04-30',
  },
  {
    id: 'research-ssrn',
    title_vi: 'SSRN — Social sciences research',
    title_en: 'SSRN — Social sciences research',
    source: 'Elsevier',
    url: 'https://www.ssrn.com',
    type: 'article',
    pillar: 'thinking',
    age_min: 14,
    age_max: 16,
    why_vi: 'Preprint kinh tế, luật, business. Nơi Nobel laureates đăng paper trước.',
    why_en: 'Preprints in econ, law, business. Where Nobel laureates post first.',
    last_updated: '2026-04-30',
  },
];

// Helper functions
export function getResourcesByPillar(pillar: Resource['pillar']): Resource[] {
  return CURATED_RESOURCES.filter(r => r.pillar === pillar);
}

export function getResourcesByAge(age: number): Resource[] {
  return CURATED_RESOURCES.filter(r => age >= r.age_min && age <= r.age_max);
}

export function getResourcesFor(pillar: Resource['pillar'], age: number): Resource[] {
  return CURATED_RESOURCES.filter(
    r => r.pillar === pillar && age >= r.age_min && age <= r.age_max
  );
}
