// Quiz bank for Pany Kids Studio.
// Curated by Bố Bình + Đại Ka. Each question is bilingual VN+EN.
// Sources: Khan Academy, Code.org, Cambridge English, BBC Learning, Junior Achievement,
// Investopedia kids, Wikipedia, NatGeo Kids, Common Sense Education.

export type QuizQuestion = {
  pillar: 'tech' | 'english' | 'finance' | 'thinking' | 'business' | 'life';
  age: '6-7' | '8-10' | '11-13' | '14-16';
  vi_q: string;
  en_q: string;
  vi_options: string[];
  en_options: string[];
  answer: number; // index 0-3
  vi_explain?: string;
  en_explain?: string;
};

export const QUIZ_BANK: QuizQuestion[] = [
  // ============ TECH (16) ============
  // 6-7
  { pillar: 'tech', age: '6-7',
    vi_q: 'Robot Bee-Bot di chuyển khi con bấm nút nào?', en_q: 'Bee-Bot robot moves when you press what?',
    vi_options: ['Mũi tên', 'Chữ A', 'Số 1', 'Hình tròn'], en_options: ['Arrows', 'Letter A', 'Number 1', 'Circle'], answer: 0,
    vi_explain: 'Bee-Bot có 4 nút mũi tên: tới, lui, trái, phải.', en_explain: 'Bee-Bot has 4 arrow buttons: forward, back, left, right.' },
  { pillar: 'tech', age: '6-7',
    vi_q: 'Lập trình là làm cái gì?', en_q: 'What is coding?',
    vi_options: ['Bảo máy tính làm việc', 'Ăn kẹo', 'Vẽ tranh', 'Nhảy múa'], en_options: ['Telling computer what to do', 'Eating candy', 'Drawing', 'Dancing'], answer: 0 },
  { pillar: 'tech', age: '6-7',
    vi_q: 'Trong ScratchJr, khối nào để cho mèo chạy?', en_q: 'In ScratchJr, which block makes the cat move?',
    vi_options: ['Mũi tên xanh', 'Hình vuông đỏ', 'Hình tam giác', 'Số 0'], en_options: ['Green arrow', 'Red square', 'Triangle', 'Zero'], answer: 0 },
  { pillar: 'tech', age: '6-7',
    vi_q: 'Máy tính nhận lệnh từ đâu?', en_q: 'Where does a computer get commands from?',
    vi_options: ['Code (chương trình)', 'Mặt trời', 'Cái bánh', 'Cây xanh'], en_options: ['Code (program)', 'The sun', 'A cake', 'A tree'], answer: 0 },

  // 8-10
  { pillar: 'tech', age: '8-10',
    vi_q: 'Trong Scratch, lệnh nào lặp lại 10 lần?', en_q: 'In Scratch, which block repeats 10 times?',
    vi_options: ['repeat 10', 'forever', 'wait 10', 'if-then'], en_options: ['repeat 10', 'forever', 'wait 10', 'if-then'], answer: 0 },
  { pillar: 'tech', age: '8-10',
    vi_q: 'Khối "forever" trong Scratch nghĩa là gì?', en_q: 'What does the "forever" block mean in Scratch?',
    vi_options: ['Lặp mãi mãi', 'Lặp 1 lần', 'Dừng lại', 'Chạy ngược'], en_options: ['Loop forever', 'Loop once', 'Stop', 'Run backwards'], answer: 0 },
  { pillar: 'tech', age: '8-10',
    vi_q: 'Algorithm là gì?', en_q: 'What is an algorithm?',
    vi_options: ['Các bước giải vấn đề', 'Trò chơi', 'Phép cộng', 'Cái máy'], en_options: ['Steps to solve a problem', 'A game', 'Addition', 'A machine'], answer: 0 },
  { pillar: 'tech', age: '8-10',
    vi_q: 'Bug trong code là gì?', en_q: 'What is a "bug" in code?',
    vi_options: ['Lỗi', 'Côn trùng thật', 'Tên file', 'Bài hát'], en_options: ['An error', 'A real insect', 'A filename', 'A song'], answer: 0 },
  { pillar: 'tech', age: '8-10',
    vi_q: 'Variable trong Scratch dùng để làm gì?', en_q: 'What is a variable for in Scratch?',
    vi_options: ['Lưu giá trị', 'Tô màu', 'Phát nhạc', 'Kết thúc game'], en_options: ['Store a value', 'Color in', 'Play music', 'End game'], answer: 0 },

  // 11-13
  { pillar: 'tech', age: '11-13',
    vi_q: 'Python: lệnh in ra màn hình là gì?', en_q: 'Python: which prints to screen?',
    vi_options: ['print()', 'console.log()', 'echo', 'show()'], en_options: ['print()', 'console.log()', 'echo', 'show()'], answer: 0 },
  { pillar: 'tech', age: '11-13',
    vi_q: 'HTML là viết tắt của gì?', en_q: 'What does HTML stand for?',
    vi_options: ['HyperText Markup Language', 'High Tech Modern Lang', 'Hot Tea Mix Lemon', 'Hyper Total Math Logic'],
    en_options: ['HyperText Markup Language', 'High Tech Modern Lang', 'Hot Tea Mix Lemon', 'Hyper Total Math Logic'], answer: 0 },
  { pillar: 'tech', age: '11-13',
    vi_q: 'CSS dùng để làm gì cho website?', en_q: 'What does CSS do for a website?',
    vi_options: ['Styling (màu, font, layout)', 'Database', 'Send email', 'Load 3D models'],
    en_options: ['Styling (colors, fonts, layout)', 'Database', 'Send email', 'Load 3D models'], answer: 0 },
  { pillar: 'tech', age: '11-13',
    vi_q: 'Trong Python, type của số "3.14" là?', en_q: 'In Python, what type is "3.14"?',
    vi_options: ['float', 'int', 'string', 'bool'], en_options: ['float', 'int', 'string', 'bool'], answer: 0 },
  { pillar: 'tech', age: '11-13',
    vi_q: 'GitHub là nơi để làm gì?', en_q: 'What is GitHub for?',
    vi_options: ['Lưu code + cộng tác', 'Mua sắm', 'Xem phim', 'Học tiếng Anh'],
    en_options: ['Host code + collaborate', 'Shopping', 'Watch movies', 'Learn English'], answer: 0 },

  // 14-16
  { pillar: 'tech', age: '14-16',
    vi_q: 'API là viết tắt của gì?', en_q: 'What does API stand for?',
    vi_options: ['Application Programming Interface', 'Apple Pie Interface', 'Auto Print Index', 'Async Process Init'],
    en_options: ['Application Programming Interface', 'Apple Pie Interface', 'Auto Print Index', 'Async Process Init'], answer: 0 },
  { pillar: 'tech', age: '14-16',
    vi_q: 'Trong React, useState dùng để làm gì?', en_q: 'In React, what is useState for?',
    vi_options: ['Quản lý state component', 'Render server', 'Connect database', 'Auth user'],
    en_options: ['Manage component state', 'Server render', 'Connect database', 'Auth user'], answer: 0 },
  { pillar: 'tech', age: '14-16',
    vi_q: 'JSON là viết tắt của gì?', en_q: 'What does JSON stand for?',
    vi_options: ['JavaScript Object Notation', 'Java Standard Object Net', 'JSet Online Number', 'Just Some Other Notation'],
    en_options: ['JavaScript Object Notation', 'Java Standard Object Net', 'JSet Online Number', 'Just Some Other Notation'], answer: 0 },

  // ============ ENGLISH (16) ============
  // 6-7
  { pillar: 'english', age: '6-7',
    vi_q: '"Cat" trong tiếng Anh nghĩa là gì?', en_q: 'What does "cat" mean?',
    vi_options: ['Mèo', 'Chó', 'Cá', 'Chim'], en_options: ['Mèo (Cat)', 'Chó (Dog)', 'Cá (Fish)', 'Chim (Bird)'], answer: 0 },
  { pillar: 'english', age: '6-7',
    vi_q: 'Số "5" trong tiếng Anh đọc là?', en_q: 'How do you say "5" in English?',
    vi_options: ['Five', 'Four', 'Six', 'Seven'], en_options: ['Five', 'Four', 'Six', 'Seven'], answer: 0 },
  { pillar: 'english', age: '6-7',
    vi_q: '"Hello" nghĩa là gì?', en_q: 'What does "Hello" mean?',
    vi_options: ['Xin chào', 'Tạm biệt', 'Cảm ơn', 'Xin lỗi'], en_options: ['Hello (greeting)', 'Goodbye', 'Thank you', 'Sorry'], answer: 0 },
  { pillar: 'english', age: '6-7',
    vi_q: 'Màu "red" là màu gì?', en_q: 'What color is "red"?',
    vi_options: ['Đỏ', 'Xanh', 'Vàng', 'Đen'], en_options: ['Red', 'Blue', 'Yellow', 'Black'], answer: 0 },

  // 8-10
  { pillar: 'english', age: '8-10',
    vi_q: 'Từ "happy" nghĩa là gì?', en_q: 'What does "happy" mean?',
    vi_options: ['Vui', 'Buồn', 'Tức giận', 'Sợ'], en_options: ['Joyful', 'Sad', 'Angry', 'Scared'], answer: 0 },
  { pillar: 'english', age: '8-10',
    vi_q: 'Plural của "child" là gì?', en_q: 'What is the plural of "child"?',
    vi_options: ['children', 'childs', 'childes', 'childer'], en_options: ['children', 'childs', 'childes', 'childer'], answer: 0 },
  { pillar: 'english', age: '8-10',
    vi_q: '"I _____ to school" — điền từ đúng', en_q: '"I _____ to school" — fill correctly',
    vi_options: ['go', 'goes', 'going', 'gone'], en_options: ['go', 'goes', 'going', 'gone'], answer: 0 },
  { pillar: 'english', age: '8-10',
    vi_q: 'Article nào đứng trước "apple"?', en_q: 'Which article goes before "apple"?',
    vi_options: ['an', 'a', 'the only', 'no article'], en_options: ['an', 'a', 'the only', 'no article'], answer: 0,
    vi_explain: '"an" trước nguyên âm a/e/i/o/u', en_explain: '"an" before vowel sounds.' },
  { pillar: 'english', age: '8-10',
    vi_q: 'Đối lập của "big" là gì?', en_q: 'Opposite of "big"?',
    vi_options: ['small', 'huge', 'tall', 'fat'], en_options: ['small', 'huge', 'tall', 'fat'], answer: 0 },

  // 11-13
  { pillar: 'english', age: '11-13',
    vi_q: 'Past tense của "go" là?', en_q: 'Past tense of "go"?',
    vi_options: ['went', 'goed', 'gone', 'going'], en_options: ['went', 'goed', 'gone', 'going'], answer: 0 },
  { pillar: 'english', age: '11-13',
    vi_q: 'Trong câu "She is reading a book", "reading" là?', en_q: 'In "She is reading a book", "reading" is what?',
    vi_options: ['Present continuous', 'Past simple', 'Future', 'Past perfect'],
    en_options: ['Present continuous', 'Past simple', 'Future', 'Past perfect'], answer: 0 },
  { pillar: 'english', age: '11-13',
    vi_q: '"Although" có nghĩa gần với từ nào?', en_q: '"Although" is close in meaning to?',
    vi_options: ['Even though', 'Because', 'And', 'Therefore'],
    en_options: ['Even though', 'Because', 'And', 'Therefore'], answer: 0 },
  { pillar: 'english', age: '11-13',
    vi_q: 'Câu "If I were rich..." là?', en_q: '"If I were rich..." is what tense?',
    vi_options: ['Conditional 2 (giả định)', 'Conditional 1', 'Present perfect', 'Past perfect'],
    en_options: ['Second conditional (hypothetical)', 'First conditional', 'Present perfect', 'Past perfect'], answer: 0 },

  // 14-16
  { pillar: 'english', age: '14-16',
    vi_q: 'Cambridge KET tương đương level CEFR nào?', en_q: 'Cambridge KET = which CEFR level?',
    vi_options: ['A2', 'B1', 'B2', 'C1'], en_options: ['A2', 'B1', 'B2', 'C1'], answer: 0 },
  { pillar: 'english', age: '14-16',
    vi_q: '"Ubiquitous" gần nghĩa với từ nào?', en_q: 'Synonym of "ubiquitous"?',
    vi_options: ['Everywhere', 'Rare', 'Old', 'Hidden'], en_options: ['Everywhere', 'Rare', 'Old', 'Hidden'], answer: 0 },
  { pillar: 'english', age: '14-16',
    vi_q: 'Trong essay, "thesis statement" là?', en_q: 'What is a "thesis statement" in an essay?',
    vi_options: ['Câu chính nêu luận điểm', 'Tiêu đề', 'Kết luận', 'Tài liệu tham khảo'],
    en_options: ['Main argument sentence', 'Title', 'Conclusion', 'References'], answer: 0 },

  // ============ FINANCE (12) ============
  { pillar: 'finance', age: '6-7',
    vi_q: '1000đ + 2000đ = ?', en_q: '1000đ + 2000đ = ?',
    vi_options: ['3000đ', '12000đ', '1200đ', '300đ'], en_options: ['3000đ', '12000đ', '1200đ', '300đ'], answer: 0 },
  { pillar: 'finance', age: '6-7',
    vi_q: 'Tiền dùng để làm gì?', en_q: 'What is money used for?',
    vi_options: ['Mua đồ', 'Để ăn', 'Để chơi', 'Để vẽ'], en_options: ['Buy things', 'To eat', 'To play with', 'To draw'], answer: 0 },
  { pillar: 'finance', age: '6-7',
    vi_q: 'Hũ "tiết kiệm" để làm gì?', en_q: 'What is the "save" jar for?',
    vi_options: ['Để dành mua đồ lớn', 'Đếm tiền', 'Tô màu', 'Vẽ'], en_options: ['Save for big items', 'Count money', 'Color', 'Draw'], answer: 0 },

  { pillar: 'finance', age: '8-10',
    vi_q: 'Hệ thống 3 hũ: Hũ Tiêu là bao nhiêu %?', en_q: '3-jar system: Spend jar is what %?',
    vi_options: ['50%', '40%', '10%', '100%'], en_options: ['50%', '40%', '10%', '100%'], answer: 0 },
  { pillar: 'finance', age: '8-10',
    vi_q: 'Cần vs Muốn: nước uống thuộc loại nào?', en_q: 'Need vs Want: drinking water is which?',
    vi_options: ['Cần (Need)', 'Muốn (Want)', 'Cả hai', 'Không phải gì cả'],
    en_options: ['Need', 'Want', 'Both', 'Neither'], answer: 0 },
  { pillar: 'finance', age: '8-10',
    vi_q: 'Tiết kiệm là gì?', en_q: 'What is "saving" money?',
    vi_options: ['Để dành tiền cho sau', 'Cho người khác', 'Vứt đi', 'In thêm'],
    en_options: ['Keep money for later', 'Give to others', 'Throw away', 'Print more'], answer: 0 },

  { pillar: 'finance', age: '11-13',
    vi_q: 'Lãi - Chi phí = ?', en_q: 'Revenue - Cost = ?',
    vi_options: ['Lợi nhuận', 'Doanh thu', 'Vốn', 'Thuế'], en_options: ['Profit', 'Revenue', 'Capital', 'Tax'], answer: 0 },
  { pillar: 'finance', age: '11-13',
    vi_q: 'Budget là gì?', en_q: 'What is a budget?',
    vi_options: ['Kế hoạch tiêu/tiết kiệm', 'Tiền mặt', 'Sổ ghi chép', 'Game tài chính'],
    en_options: ['Plan for spending/saving', 'Cash', 'Notebook', 'Finance game'], answer: 0 },
  { pillar: 'finance', age: '11-13',
    vi_q: 'ATM viết tắt của gì?', en_q: 'What does ATM stand for?',
    vi_options: ['Automated Teller Machine', 'All Time Money', 'Advanced Tax Module', 'Auto Transaction Memo'],
    en_options: ['Automated Teller Machine', 'All Time Money', 'Advanced Tax Module', 'Auto Transaction Memo'], answer: 0 },

  { pillar: 'finance', age: '14-16',
    vi_q: 'Lãi suất kép có nghĩa là?', en_q: 'Compound interest means?',
    vi_options: ['Lãi sinh ra lãi', 'Lãi cố định', 'Không có lãi', 'Lãi giảm'],
    en_options: ['Interest on interest', 'Fixed interest', 'No interest', 'Decreasing interest'], answer: 0 },
  { pillar: 'finance', age: '14-16',
    vi_q: 'Cổ phiếu (stock) là gì?', en_q: 'What is a stock?',
    vi_options: ['Phần sở hữu công ty', 'Khoản vay', 'Tiền mặt', 'Sản phẩm'],
    en_options: ['Ownership share of company', 'A loan', 'Cash', 'A product'], answer: 0 },
  { pillar: 'finance', age: '14-16',
    vi_q: 'Diversification (đa dạng hoá) trong đầu tư có nghĩa là?', en_q: 'Diversification in investing means?',
    vi_options: ['Không bỏ trứng vào 1 giỏ', 'Mua 1 cổ phiếu duy nhất', 'Bán hết', 'Chỉ giữ tiền mặt'],
    en_options: ['Not all eggs in 1 basket', 'Buy only 1 stock', 'Sell everything', 'Hold only cash'], answer: 0 },

  // ============ THINKING (10) ============
  { pillar: 'thinking', age: '8-10',
    vi_q: 'Khi không biết 1 thông tin, con nên làm gì đầu tiên?', en_q: 'When you don\'t know something, what to do first?',
    vi_options: ['Đoán + kiểm tra với bố/mẹ', 'Tin ngay quảng cáo', 'Bỏ qua', 'Khóc'],
    en_options: ['Guess + verify with parents', 'Trust ads immediately', 'Skip it', 'Cry'], answer: 0 },
  { pillar: 'thinking', age: '8-10',
    vi_q: 'Logic: Tất cả mèo đều có 4 chân. Tom là mèo. Vậy Tom có?', en_q: 'Logic: All cats have 4 legs. Tom is a cat. So Tom has?',
    vi_options: ['4 chân', '2 chân', '6 chân', 'Không có chân'],
    en_options: ['4 legs', '2 legs', '6 legs', 'No legs'], answer: 0 },
  { pillar: 'thinking', age: '8-10',
    vi_q: 'Câu hỏi nào sau đây "open-ended"?', en_q: 'Which is an "open-ended" question?',
    vi_options: ['Tại sao trời mưa?', 'Có/Không?', '1 hay 2?', 'Đỏ hay xanh?'],
    en_options: ['Why does it rain?', 'Yes/No?', '1 or 2?', 'Red or blue?'], answer: 0 },

  { pillar: 'thinking', age: '11-13',
    vi_q: 'Logical fallacy "ad hominem" nghĩa là?', en_q: '"Ad hominem" fallacy means?',
    vi_options: ['Tấn công cá nhân thay vì lý lẽ', 'Lập luận đúng', 'Cho ví dụ', 'Tóm tắt'],
    en_options: ['Attack person not argument', 'Valid argument', 'Give example', 'Summarize'], answer: 0 },
  { pillar: 'thinking', age: '11-13',
    vi_q: '"Confirmation bias" là gì?', en_q: 'What is "confirmation bias"?',
    vi_options: ['Chỉ tin info xác nhận quan điểm sẵn', 'Tin mọi thứ', 'Nghi mọi thứ', 'Đoán mò'],
    en_options: ['Only believing info that confirms your view', 'Believing everything', 'Doubting everything', 'Random guessing'], answer: 0 },
  { pillar: 'thinking', age: '11-13',
    vi_q: 'Khi đọc 1 fact mới, nên kiểm bao nhiêu nguồn?', en_q: 'When reading a new fact, how many sources to check?',
    vi_options: ['Ít nhất 3 nguồn khác nhau', '0 — tin ngay', '1 nguồn duy nhất', '100 nguồn'],
    en_options: ['At least 3 different sources', '0 — believe immediately', 'Only 1 source', '100 sources'], answer: 0 },
  { pillar: 'thinking', age: '11-13',
    vi_q: 'Logical fallacy "straw man" là?', en_q: 'What is "straw man" fallacy?',
    vi_options: ['Bóp méo quan điểm đối phương để dễ bác bỏ', 'Đưa số liệu', 'Trích dẫn nguồn', 'Đặt câu hỏi'],
    en_options: ['Distorting opponent\'s view to refute easily', 'Citing data', 'Quoting source', 'Asking question'], answer: 0 },

  { pillar: 'thinking', age: '14-16',
    vi_q: '"Occam\'s Razor" là gì?', en_q: 'What is "Occam\'s Razor"?',
    vi_options: ['Giải thích đơn giản nhất thường đúng', 'Cạo râu', 'Định luật vật lý', 'Sách lịch sử'],
    en_options: ['Simplest explanation often right', 'A real razor', 'Physics law', 'History book'], answer: 0 },
  { pillar: 'thinking', age: '14-16',
    vi_q: '"Dunning-Kruger effect" là?', en_q: 'What is "Dunning-Kruger effect"?',
    vi_options: ['Người ít hiểu biết tự tin quá mức', 'Hiệu ứng nhiệt', 'Định luật toán', 'Bài hát pop'],
    en_options: ['Less knowledgeable people overestimate themselves', 'Heat effect', 'Math law', 'Pop song'], answer: 0 },
  { pillar: 'thinking', age: '14-16',
    vi_q: 'Trong tranh luận, "steel-manning" nghĩa là?', en_q: 'In debate, "steel-manning" means?',
    vi_options: ['Trình bày quan điểm đối phương ở phiên bản mạnh nhất', 'Tấn công cá nhân', 'Bỏ qua đối phương', 'Hét to'],
    en_options: ['Present opponent\'s view in strongest form', 'Attack personally', 'Ignore opponent', 'Shout'], answer: 0 },

  // ============ BUSINESS (8) ============
  { pillar: 'business', age: '8-10',
    vi_q: 'Bán 1 ly nước 5000đ, vốn 2000đ. Lãi bao nhiêu?', en_q: 'Sell juice 5000đ, cost 2000đ. Profit?',
    vi_options: ['3000đ', '7000đ', '2000đ', '5000đ'], en_options: ['3000đ', '7000đ', '2000đ', '5000đ'], answer: 0 },
  { pillar: 'business', age: '8-10',
    vi_q: 'Khách hàng là ai?', en_q: 'Who is a customer?',
    vi_options: ['Người mua sản phẩm', 'Người bán', 'Người làm sản phẩm', 'Bố/mẹ'],
    en_options: ['Person who buys', 'Seller', 'Maker', 'Parent'], answer: 0 },

  { pillar: 'business', age: '11-13',
    vi_q: 'ROI viết tắt của gì?', en_q: 'What does ROI stand for?',
    vi_options: ['Return on Investment', 'Rate of Income', 'Real Output Index', 'Run on Internet'],
    en_options: ['Return on Investment', 'Rate of Income', 'Real Output Index', 'Run on Internet'], answer: 0 },
  { pillar: 'business', age: '11-13',
    vi_q: 'Marketing có 4P. Đó là?', en_q: '4Ps of marketing are?',
    vi_options: ['Product, Price, Place, Promotion', 'People, Plan, Power, Profit', 'Pay, Push, Pull, Pause', 'Past, Present, Plan, Plot'],
    en_options: ['Product, Price, Place, Promotion', 'People, Plan, Power, Profit', 'Pay, Push, Pull, Pause', 'Past, Present, Plan, Plot'], answer: 0 },
  { pillar: 'business', age: '11-13',
    vi_q: 'B2B nghĩa là?', en_q: 'B2B means?',
    vi_options: ['Business to Business', 'Buy to Buy', 'Big to Big', 'Bot to Bot'],
    en_options: ['Business to Business', 'Buy to Buy', 'Big to Big', 'Bot to Bot'], answer: 0 },

  { pillar: 'business', age: '14-16',
    vi_q: 'MVP trong startup là gì?', en_q: 'What is MVP in startup?',
    vi_options: ['Minimum Viable Product', 'Most Valuable Player', 'Major Value Proposition', 'Multi Vendor Platform'],
    en_options: ['Minimum Viable Product', 'Most Valuable Player', 'Major Value Proposition', 'Multi Vendor Platform'], answer: 0 },
  { pillar: 'business', age: '14-16',
    vi_q: 'Pivot trong startup nghĩa là?', en_q: 'What does "pivot" mean in startup?',
    vi_options: ['Đổi hướng business model', 'Đóng cửa', 'Tăng giá', 'Sa thải nhân viên'],
    en_options: ['Change business direction', 'Shut down', 'Raise price', 'Fire staff'], answer: 0 },
  { pillar: 'business', age: '14-16',
    vi_q: 'Burn rate là gì?', en_q: 'What is burn rate?',
    vi_options: ['Tốc độ tiêu tiền/tháng', 'Nhiệt độ động cơ', 'Tốc độ chạy', 'Lửa thật'],
    en_options: ['Cash spent per month', 'Engine temperature', 'Running speed', 'Real fire'], answer: 0 },

  // ============ LIFE (8) ============
  { pillar: 'life', age: '6-7',
    vi_q: 'Việt Nam có bao nhiêu mùa?', en_q: 'How many seasons in Vietnam?',
    vi_options: ['4 (xuân hạ thu đông)', '2', '3', '5'], en_options: ['4 (spring/summer/fall/winter)', '2', '3', '5'], answer: 0 },
  { pillar: 'life', age: '6-7',
    vi_q: 'Mặt trời mọc ở hướng nào?', en_q: 'Sun rises from which direction?',
    vi_options: ['Đông', 'Tây', 'Nam', 'Bắc'], en_options: ['East', 'West', 'South', 'North'], answer: 0 },

  { pillar: 'life', age: '8-10',
    vi_q: 'Thủ đô Việt Nam là?', en_q: 'Capital of Vietnam?',
    vi_options: ['Hà Nội', 'Sài Gòn', 'Đà Nẵng', 'Huế'], en_options: ['Hà Nội', 'Hồ Chí Minh City', 'Đà Nẵng', 'Huế'], answer: 0 },
  { pillar: 'life', age: '8-10',
    vi_q: 'VN có bao nhiêu dân tộc?', en_q: 'How many ethnic groups in VN?',
    vi_options: ['54', '10', '100', '20'], en_options: ['54', '10', '100', '20'], answer: 0 },

  { pillar: 'life', age: '11-13',
    vi_q: 'Sông dài nhất Việt Nam là?', en_q: 'Longest river in Vietnam?',
    vi_options: ['Mê Kông', 'Hồng', 'Đồng Nai', 'Hương'], en_options: ['Mekong', 'Red River', 'Đồng Nai', 'Hương'], answer: 0 },
  { pillar: 'life', age: '11-13',
    vi_q: 'Cao nhất Việt Nam là núi nào?', en_q: 'Highest peak in Vietnam?',
    vi_options: ['Fansipan (3143m)', 'Bà Đen', 'Lang Biang', 'Yên Tử'],
    en_options: ['Fansipan (3143m)', 'Bà Đen', 'Lang Biang', 'Yên Tử'], answer: 0 },

  { pillar: 'life', age: '14-16',
    vi_q: 'Hiện tượng El Niño ảnh hưởng đến VN ra sao?', en_q: 'How does El Niño affect Vietnam?',
    vi_options: ['Hạn hán + thiếu mưa', 'Lụt nhiều', 'Lạnh hơn', 'Không ảnh hưởng'],
    en_options: ['Drought + less rain', 'More floods', 'Colder', 'No effect'], answer: 0 },
  { pillar: 'life', age: '14-16',
    vi_q: 'UNESCO Việt Nam có bao nhiêu di sản (2025)?', en_q: 'How many UNESCO sites in VN (2025)?',
    vi_options: ['9', '5', '15', '3'], en_options: ['9', '5', '15', '3'], answer: 0,
    vi_explain: 'Hạ Long, Phong Nha, Mỹ Sơn, Hội An, Huế, Tràng An, Thành Nhà Hồ, Hoàng thành Thăng Long, Cát Bà.', en_explain: 'Hạ Long, Phong Nha, Mỹ Sơn, Hội An, Huế, Tràng An, Hồ Citadel, Thăng Long, Cát Bà.' },
];
