// 60 Career Cards — 10 per RIASEC type, with Vietnam context
// Designed for kids 8-15 to explore career possibilities

import type { RiasecType } from './riasec-junior';

export interface Career {
  id: string;
  type: RiasecType;
  vi_name: string;
  en_name: string;
  emoji: string;
  vi_desc: string;
  en_desc: string;
  vi_skills: string[];
  en_skills: string[];
  vi_path: string;
  en_path: string;
  vn_context: string;
  vn_salary?: string;
  vn_example?: string;
  min_age: number;
}

export const CAREERS: Career[] = [
  // ============== R — Realistic (10) ==============
  { id: 'mech_eng', type: 'R', emoji: '🔧', min_age: 10,
    vi_name: 'Kỹ sư cơ khí', en_name: 'Mechanical Engineer',
    vi_desc: 'Thiết kế và chế tạo máy móc — từ xe ô tô đến robot',
    en_desc: 'Design and build machines — from cars to robots',
    vi_skills: ['Toán', 'Vật lý', 'Vẽ kỹ thuật', 'Sửa chữa', 'Lắp ráp Lego/mô hình'],
    en_skills: ['Math', 'Physics', 'Drafting', 'Repair', 'Lego/model building'],
    vi_path: 'Bắt đầu chơi Lego Technic + xem YouTube cách máy hoạt động → học giỏi Toán Lý cấp 3 → Đại học Bách Khoa',
    en_path: 'Start with Lego Technic + watch how-things-work videos → strong Math/Physics in high school → engineering university',
    vn_context: 'VN cần kỹ sư cho VinFast, Samsung, Intel — lương khởi điểm 12-25tr',
    vn_example: 'CEO VinFast Phạm Nhật Vượng đầu tư hàng tỷ USD vào ngành cơ khí ô tô VN',
    vn_salary: '12-50tr/tháng',
  },
  { id: 'architect', type: 'R', emoji: '🏛️', min_age: 9,
    vi_name: 'Kiến trúc sư', en_name: 'Architect',
    vi_desc: 'Thiết kế nhà, văn phòng, công viên — nơi mọi người sống và làm việc',
    en_desc: 'Design houses, offices, parks — places where people live and work',
    vi_skills: ['Vẽ', 'Toán hình học', 'Sáng tạo', 'AutoCAD/SketchUp', 'Quan sát công trình'],
    en_skills: ['Drawing', 'Geometry', 'Creativity', 'AutoCAD/SketchUp', 'Observation'],
    vi_path: 'Vẽ nhà mơ ước → học vẽ kỹ thuật → Đại học Kiến trúc HCM/HN',
    en_path: 'Draw dream houses → study technical drawing → architecture university',
    vn_context: 'Đô thị hóa VN tăng nhanh — nhu cầu KTS cho dự án chung cư, resort',
    vn_example: 'KTS Võ Trọng Nghĩa nổi tiếng thế giới với kiến trúc xanh tre nứa',
    vn_salary: '15-80tr/tháng',
  },
  { id: 'vet', type: 'R', emoji: '🐾', min_age: 8,
    vi_name: 'Bác sĩ thú y', en_name: 'Veterinarian',
    vi_desc: 'Chữa bệnh cho động vật — từ chó mèo đến trâu bò, voi, tê giác',
    en_desc: 'Heal animals — from dogs/cats to elephants and rhinos',
    vi_skills: ['Yêu động vật', 'Sinh học', 'Kiên nhẫn', 'Bình tĩnh', 'Khéo tay'],
    en_skills: ['Love for animals', 'Biology', 'Patience', 'Calmness', 'Dexterity'],
    vi_path: 'Nuôi thú cưng + tình nguyện shelter → học giỏi Sinh → Đại học Nông Lâm',
    en_path: 'Care for pets + volunteer at shelters → strong Biology → vet school',
    vn_context: 'Pet care market VN tăng 20%/năm, phòng khám thú y mở rộng đô thị',
    vn_salary: '10-30tr/tháng',
  },
  { id: 'pilot', type: 'R', emoji: '✈️', min_age: 11,
    vi_name: 'Phi công', en_name: 'Pilot',
    vi_desc: 'Lái máy bay đưa hành khách đi khắp thế giới',
    en_desc: 'Fly planes taking passengers around the world',
    vi_skills: ['Toán', 'Vật lý', 'Tiếng Anh', 'Phản xạ nhanh', 'Sức khoẻ tốt'],
    en_skills: ['Math', 'Physics', 'English', 'Quick reflexes', 'Strong health'],
    vi_path: 'Học giỏi Anh + Toán Lý → thi vào học viện Hàng không (BAA, Vietravel)',
    en_path: 'Excel in English + Math/Physics → aviation academy (BAA, Vietravel)',
    vn_context: 'VN Airlines/VietJet/Bamboo cần phi công — lương 80-300tr/tháng',
    vn_salary: '80-300tr/tháng',
  },
  { id: 'chef', type: 'R', emoji: '👨‍🍳', min_age: 8,
    vi_name: 'Đầu bếp', en_name: 'Chef',
    vi_desc: 'Sáng tạo món ăn ngon, quản lý nhà bếp — từ phở Việt đến fine-dining quốc tế',
    en_desc: 'Create delicious dishes, manage kitchens — from phở to fine dining',
    vi_skills: ['Vị giác tốt', 'Sáng tạo', 'Nhanh tay', 'Quản lý', 'Sạch sẽ'],
    en_skills: ['Good palate', 'Creativity', 'Speed', 'Management', 'Hygiene'],
    vi_path: 'Tự nấu ở nhà + xem MasterChef → trường Saigontourist/Hanoi Tourism',
    en_path: 'Cook at home + watch MasterChef → culinary school',
    vn_context: 'F&B VN bùng nổ với chuỗi nhà hàng, du lịch 18 triệu khách quốc tế',
    vn_example: 'Đầu bếp Christine Hà mù 100% vẫn vô địch MasterChef US',
    vn_salary: '8-50tr/tháng',
  },
  { id: 'farmer', type: 'R', emoji: '🌾', min_age: 9,
    vi_name: 'Nông dân công nghệ cao', en_name: 'AgriTech Farmer',
    vi_desc: 'Trồng rau, hoa, quả bằng công nghệ — nhà kính, IoT, hữu cơ',
    en_desc: 'Grow vegetables/fruits with tech — greenhouses, IoT, organic',
    vi_skills: ['Sinh học', 'Công nghệ', 'Kiên trì', 'Quan sát', 'Kinh doanh'],
    en_skills: ['Biology', 'Technology', 'Patience', 'Observation', 'Business'],
    vi_path: 'Trồng cây tại nhà + theo dõi → Đại học Nông Lâm chuyên AgriTech',
    en_path: 'Grow plants at home + tracking → AgriTech program at agriculture university',
    vn_context: 'VN xuất khẩu nông sản top 10 thế giới — Vinamilk, TH True Milk dùng IoT',
    vn_salary: '15-100tr/tháng (tự kinh doanh)',
  },
  { id: 'electrician', type: 'R', emoji: '⚡', min_age: 12,
    vi_name: 'Thợ điện chuyên nghiệp', en_name: 'Electrician',
    vi_desc: 'Lắp đặt và sửa chữa hệ thống điện — nhà ở, văn phòng, nhà máy',
    en_desc: 'Install and repair electrical systems — homes, offices, factories',
    vi_skills: ['Vật lý', 'Cẩn thận', 'Sức khoẻ tay', 'Đọc sơ đồ', 'An toàn lao động'],
    en_skills: ['Physics', 'Carefulness', 'Hand strength', 'Schematic reading', 'Safety'],
    vi_path: 'Học nghề trung cấp/cao đẳng kỹ thuật điện 2-3 năm',
    en_path: 'Vocational school 2-3 years in electrical tech',
    vn_context: 'Smart home + nhà máy FDI cần thợ điện cao cấp gấp',
    vn_salary: '8-30tr/tháng',
  },
  { id: 'sport_coach', type: 'R', emoji: '🏋️', min_age: 10,
    vi_name: 'Huấn luyện viên thể thao', en_name: 'Sports Coach',
    vi_desc: 'Dạy người khác chơi thể thao, tập gym, yoga — giúp họ khoẻ mạnh',
    en_desc: 'Teach others sports, gym, yoga — help them get healthy',
    vi_skills: ['Sức khoẻ', 'Truyền cảm hứng', 'Kiến thức cơ thể', 'Kiên nhẫn', 'Giao tiếp'],
    en_skills: ['Fitness', 'Inspiration', 'Body knowledge', 'Patience', 'Communication'],
    vi_path: 'Chơi thể thao học đường → chứng chỉ HLV (FISAF, AFAA) → Đại học TDTT',
    en_path: 'School sports → coaching certs → sports university',
    vn_context: 'Gym/yoga/CrossFit VN tăng 30%/năm sau dịch — California, Elite Fitness',
    vn_salary: '10-60tr/tháng + commission',
  },
  { id: 'explorer', type: 'R', emoji: '🗺️', min_age: 10,
    vi_name: 'Nhà thám hiểm/Địa chất', en_name: 'Explorer/Geologist',
    vi_desc: 'Khám phá hang động, núi, đại dương — phát hiện khoáng sản, hoá thạch',
    en_desc: 'Explore caves, mountains, oceans — discover minerals, fossils',
    vi_skills: ['Sức khoẻ', 'Khoa học trái đất', 'Bản đồ', 'Bình tĩnh', 'Tiếng Anh'],
    en_skills: ['Fitness', 'Earth science', 'Maps', 'Calmness', 'English'],
    vi_path: 'Đi phượt + đọc NatGeo → Đại học Địa chất/Mỏ',
    en_path: 'Trek + read NatGeo → geology/mining university',
    vn_context: 'Sơn Đoòng — hang động lớn nhất thế giới ở Quảng Bình do người Việt khám phá',
    vn_example: 'Hồ Khanh — người tìm ra hang Sơn Đoòng',
    vn_salary: '15-80tr/tháng',
  },
  { id: 'firefighter', type: 'R', emoji: '🚒', min_age: 12,
    vi_name: 'Lính cứu hoả', en_name: 'Firefighter',
    vi_desc: 'Cứu người và cứu hoả — anh hùng thực sự của thành phố',
    en_desc: 'Rescue people and fight fires — real city heroes',
    vi_skills: ['Sức khoẻ', 'Dũng cảm', 'Phản xạ', 'Làm việc nhóm', 'Sơ cấp cứu'],
    en_skills: ['Fitness', 'Courage', 'Reflexes', 'Teamwork', 'First aid'],
    vi_path: 'Tập thể dục + tham gia hoạt động cộng đồng → Đại học PCCC',
    en_path: 'Fitness + community activities → fire prevention college',
    vn_context: 'Lực lượng PCCC VN tuyển thường xuyên, lương ổn định + phụ cấp',
    vn_salary: '8-25tr/tháng + bảo hiểm',
  },

  // ============== I — Investigative (10) ==============
  { id: 'scientist', type: 'I', emoji: '🔬', min_age: 9,
    vi_name: 'Nhà khoa học', en_name: 'Scientist',
    vi_desc: 'Nghiên cứu để hiểu vũ trụ — từ tế bào đến lỗ đen',
    en_desc: 'Research to understand the universe — from cells to black holes',
    vi_skills: ['Toán', 'Khoa học', 'Tiếng Anh', 'Tò mò', 'Kiên nhẫn'],
    en_skills: ['Math', 'Science', 'English', 'Curiosity', 'Patience'],
    vi_path: 'Đọc sách khoa học + thi HSG Lý/Hoá/Sinh → trường chuyên → ĐH KHTN',
    en_path: 'Read science books + Olympiad → magnet school → science university',
    vn_context: 'GS Ngô Bảo Châu giành Fields Medal 2010 — niềm tự hào VN',
    vn_example: 'Ngô Bảo Châu, Đặng Thái Sơn, Châu Văn Liêm',
    vn_salary: '15-80tr/tháng',
  },
  { id: 'doctor', type: 'I', emoji: '🩺', min_age: 10,
    vi_name: 'Bác sĩ', en_name: 'Doctor',
    vi_desc: 'Chữa bệnh, cứu người — nghề nhân văn nhất',
    en_desc: 'Heal patients, save lives — the most humanitarian profession',
    vi_skills: ['Sinh học', 'Hoá học', 'Trí nhớ', 'Lòng nhân ái', 'Chịu áp lực'],
    en_skills: ['Biology', 'Chemistry', 'Memory', 'Compassion', 'Stress tolerance'],
    vi_path: 'Học giỏi Toán Hoá Sinh → ĐH Y Hà Nội/HCM (6 năm) → bác sĩ nội trú',
    en_path: 'Excel in Math/Chem/Bio → medical university (6 years) → residency',
    vn_context: 'Y khoa luôn top ngành điểm cao nhất VN, lương sau 10 năm 50-200tr',
    vn_salary: '15-200tr/tháng',
  },
  { id: 'programmer', type: 'I', emoji: '💻', min_age: 8,
    vi_name: 'Lập trình viên', en_name: 'Programmer',
    vi_desc: 'Viết code tạo app, web, game — biến ý tưởng thành phần mềm',
    en_desc: 'Write code to build apps, websites, games — turn ideas into software',
    vi_skills: ['Logic', 'Toán', 'Tiếng Anh', 'Kiên trì debug', 'Tự học'],
    en_skills: ['Logic', 'Math', 'English', 'Debugging patience', 'Self-learning'],
    vi_path: 'Học Scratch (8t) → Python (12t) → web/mobile (15t) → ĐH CNTT hoặc tự học',
    en_path: 'Scratch (age 8) → Python (12) → web/mobile (15) → CS degree or self-taught',
    vn_context: 'IT VN xuất khẩu hàng đầu — FPT, Viettel, VNG, các công ty nước ngoài',
    vn_example: 'Nguyễn Hà Đông — tác giả Flappy Bird (50tr USD)',
    vn_salary: '15-150tr/tháng',
  },
  { id: 'mathematician', type: 'I', emoji: '📐', min_age: 9,
    vi_name: 'Nhà toán học', en_name: 'Mathematician',
    vi_desc: 'Giải bài toán khó nhất thế giới — và tạo ra toán học mới',
    en_desc: 'Solve world\'s hardest problems — and invent new mathematics',
    vi_skills: ['Logic siêu phàm', 'Kiên trì', 'Tư duy trừu tượng', 'Olympiad', 'Tự học'],
    en_skills: ['Super logic', 'Persistence', 'Abstract thinking', 'Olympiad', 'Self-study'],
    vi_path: 'Olympiad Toán quốc gia → quốc tế → ĐH KHTN/Bách Khoa → PhD',
    en_path: 'National Math Olympiad → International → top university → PhD',
    vn_context: 'VN top 10 thế giới về Olympiad Toán quốc tế (IMO)',
    vn_example: 'GS Ngô Bảo Châu, GS Vũ Hà Văn (Yale)',
    vn_salary: '20-100tr/tháng (đại học) / unlimited (industry)',
  },
  { id: 'psychologist', type: 'I', emoji: '🧠', min_age: 10,
    vi_name: 'Nhà tâm lý học', en_name: 'Psychologist',
    vi_desc: 'Hiểu tâm trí con người — giúp người khác vượt qua khó khăn cảm xúc',
    en_desc: 'Understand the human mind — help others overcome emotional struggles',
    vi_skills: ['Lắng nghe', 'Kiên nhẫn', 'Đọc sách', 'Đồng cảm', 'Quan sát'],
    en_skills: ['Listening', 'Patience', 'Reading', 'Empathy', 'Observation'],
    vi_path: 'Đọc tâm lý học phổ thông → ĐH KHXH&NV → tham gia training quốc tế',
    en_path: 'Read pop psychology → social sciences university → international training',
    vn_context: 'Tâm lý học VN còn non trẻ nhưng nhu cầu tăng nhanh — tâm lý học đường',
    vn_salary: '12-80tr/tháng',
  },
  { id: 'pharmacist', type: 'I', emoji: '💊', min_age: 11,
    vi_name: 'Dược sĩ', en_name: 'Pharmacist',
    vi_desc: 'Chuyên gia về thuốc — bào chế, tư vấn, nghiên cứu thuốc mới',
    en_desc: 'Medication expert — formulate, advise, research new drugs',
    vi_skills: ['Hoá học', 'Trí nhớ tốt', 'Cẩn thận', 'Tư vấn', 'Đạo đức nghề'],
    en_skills: ['Chemistry', 'Good memory', 'Carefulness', 'Counseling', 'Ethics'],
    vi_path: 'Giỏi Toán Hoá Sinh → ĐH Dược Hà Nội/HCM (5 năm)',
    en_path: 'Excel in Math/Chem/Bio → pharmacy university (5 years)',
    vn_context: 'Chuỗi nhà thuốc VN: Long Châu, Pharmacity, An Khang mở rộng nhanh',
    vn_salary: '12-50tr/tháng',
  },
  { id: 'biologist', type: 'I', emoji: '🧬', min_age: 9,
    vi_name: 'Nhà sinh học', en_name: 'Biologist',
    vi_desc: 'Nghiên cứu sự sống — từ vi khuẩn tới đại dương, di truyền học',
    en_desc: 'Study life — from bacteria to oceans, genetics',
    vi_skills: ['Sinh học', 'Quan sát thiên nhiên', 'Kiên trì lab', 'Tiếng Anh', 'Hoá'],
    en_skills: ['Biology', 'Nature observation', 'Lab patience', 'English', 'Chemistry'],
    vi_path: 'Tham gia CLB Sinh học + thi HSG → ĐH KHTN ngành Sinh',
    en_path: 'Biology club + Olympiad → biology university',
    vn_context: 'VN có đa dạng sinh học top 16 thế giới — Cát Tiên, Cúc Phương',
    vn_salary: '12-60tr/tháng',
  },
  { id: 'ai_engineer', type: 'I', emoji: '🤖', min_age: 11,
    vi_name: 'Kỹ sư AI', en_name: 'AI Engineer',
    vi_desc: 'Xây dựng AI thông minh — như Đại Ka, ChatGPT, image generators',
    en_desc: 'Build smart AI — like Đại Ka, ChatGPT, image generators',
    vi_skills: ['Toán cao', 'Python', 'Statistics', 'Tiếng Anh', 'Sáng tạo'],
    en_skills: ['Advanced Math', 'Python', 'Statistics', 'English', 'Creativity'],
    vi_path: 'Học Python + Math → kaggle competitions → ĐH CNTT/Toán → MS AI',
    en_path: 'Python + Math → Kaggle → CS/Math university → MS in AI',
    vn_context: 'AI VN bùng nổ — VinAI, Zalo AI, FPT.AI tuyển không hết',
    vn_salary: '30-300tr/tháng',
  },
  { id: 'astronomer', type: 'I', emoji: '🔭', min_age: 9,
    vi_name: 'Nhà thiên văn', en_name: 'Astronomer',
    vi_desc: 'Nghiên cứu hành tinh, sao, lỗ đen, vũ trụ',
    en_desc: 'Study planets, stars, black holes, the universe',
    vi_skills: ['Vật lý', 'Toán', 'Tiếng Anh', 'Kiên nhẫn', 'Tò mò'],
    en_skills: ['Physics', 'Math', 'English', 'Patience', 'Curiosity'],
    vi_path: 'Tham gia Hội Thiên văn HCM/HN → Olympiad Vật lý → ĐH KHTN',
    en_path: 'Astronomy clubs → Physics Olympiad → physics university',
    vn_context: 'Đài thiên văn Hoà Lạc đang xây dựng — cộng đồng amateur sôi động',
    vn_salary: '15-60tr/tháng',
  },
  { id: 'forensic', type: 'I', emoji: '🔍', min_age: 11,
    vi_name: 'Chuyên gia pháp y', en_name: 'Forensic Expert',
    vi_desc: 'Giải mã vụ án bằng khoa học — DNA, vân tay, kỹ thuật số',
    en_desc: 'Solve cases with science — DNA, fingerprints, digital forensics',
    vi_skills: ['Hoá học', 'Sinh học', 'Quan sát chi tiết', 'Lý lẽ', 'Bình tĩnh'],
    en_skills: ['Chemistry', 'Biology', 'Detail observation', 'Logic', 'Calmness'],
    vi_path: 'Giỏi Hoá Sinh → ĐH Y/An ninh → chuyên ngành pháp y',
    en_path: 'Strong Chem/Bio → medical/security academy → forensics',
    vn_context: 'C45 Bộ Công An tuyển chuyên gia kỹ thuật hình sự',
    vn_salary: '15-50tr/tháng + phụ cấp',
  },

  // ============== A — Artistic (10) ==============
  { id: 'artist', type: 'A', emoji: '🎨', min_age: 6,
    vi_name: 'Hoạ sĩ', en_name: 'Artist',
    vi_desc: 'Vẽ tranh, sáng tạo nghệ thuật — triển lãm khắp thế giới',
    en_desc: 'Paint, create art — exhibit worldwide',
    vi_skills: ['Vẽ', 'Sáng tạo', 'Quan sát', 'Kiên trì', 'Cảm xúc'],
    en_skills: ['Drawing', 'Creativity', 'Observation', 'Persistence', 'Emotion'],
    vi_path: 'Vẽ mỗi ngày → triển lãm trường → ĐH Mỹ Thuật / tự học online',
    en_path: 'Draw daily → school exhibitions → art university or self-taught',
    vn_context: 'Nghệ thuật VN có tranh sơn dầu Phái, Tô Ngọc Vân — giá triệu đô',
    vn_example: 'Bùi Xuân Phái, Lê Phổ — tranh đấu giá $1M+',
    vn_salary: 'Bất định (5tr-vô hạn)',
  },
  { id: 'musician', type: 'A', emoji: '🎵', min_age: 6,
    vi_name: 'Nhạc sĩ', en_name: 'Musician',
    vi_desc: 'Sáng tác, trình diễn nhạc — concert, ghi âm, soundtrack phim',
    en_desc: 'Compose, perform music — concerts, recordings, film soundtracks',
    vi_skills: ['Nhạc cảm', 'Học nhạc cụ', 'Kiên trì luyện', 'Sáng tạo', 'Trình diễn'],
    en_skills: ['Musical sense', 'Instrument', 'Practice patience', 'Creativity', 'Performance'],
    vi_path: 'Học piano/guitar (6t) → Học viện Âm nhạc → producer/biểu diễn',
    en_path: 'Piano/guitar (6yo) → conservatory → producer/performer',
    vn_context: 'VPop bùng nổ — Sơn Tùng MTP, Mỹ Tâm, Đen Vâu kiếm hàng tỷ/năm',
    vn_example: 'Sơn Tùng MTP, Đặng Thái Sơn (piano)',
    vn_salary: 'Bất định (10tr-tỷ/show)',
  },
  { id: 'designer', type: 'A', emoji: '✏️', min_age: 9,
    vi_name: 'Nhà thiết kế', en_name: 'Designer',
    vi_desc: 'Thiết kế đồ hoạ, web, sản phẩm — đẹp + dễ dùng',
    en_desc: 'Design graphics, web, products — beautiful + usable',
    vi_skills: ['Vẽ', 'Figma/Photoshop', 'Tư duy thẩm mỹ', 'UX', 'Tiếng Anh'],
    en_skills: ['Drawing', 'Figma/Photoshop', 'Aesthetic sense', 'UX', 'English'],
    vi_path: 'Vẽ + Photoshop tự học → portfolio Behance → ĐH Mỹ Thuật/tự học',
    en_path: 'Draw + self-taught Photoshop → Behance portfolio → design school',
    vn_context: 'Designer VN làm cho Nike, Apple từ xa, Toptal, Dribbble nổi tiếng',
    vn_salary: '15-100tr/tháng (freelance/remote)',
  },
  { id: 'film_director', type: 'A', emoji: '🎬', min_age: 11,
    vi_name: 'Đạo diễn phim', en_name: 'Film Director',
    vi_desc: 'Tạo phim điện ảnh, web series, MV — kể chuyện qua hình ảnh',
    en_desc: 'Make films, web series, MVs — tell stories visually',
    vi_skills: ['Storytelling', 'Lãnh đạo', 'Thẩm mỹ', 'Kỹ thuật quay', 'Edit'],
    en_skills: ['Storytelling', 'Leadership', 'Aesthetics', 'Cinematography', 'Editing'],
    vi_path: 'Quay video bằng điện thoại → YouTube → ĐH Sân Khấu/SKDA',
    en_path: 'Phone videos → YouTube → film school',
    vn_context: 'VN cinema bùng nổ — Trấn Thành, Lý Hải doanh thu trăm tỷ/phim',
    vn_example: 'Phan Đăng Di, Phan Gia Nhật Linh — quốc tế',
    vn_salary: '50tr-500tr/dự án',
  },
  { id: 'writer', type: 'A', emoji: '✍️', min_age: 8,
    vi_name: 'Nhà văn', en_name: 'Writer',
    vi_desc: 'Viết tiểu thuyết, kịch bản, blog — kể chuyện bằng từ ngữ',
    en_desc: 'Write novels, scripts, blogs — tell stories with words',
    vi_skills: ['Đọc nhiều', 'Sáng tạo', 'Quan sát đời sống', 'Kiên trì', 'Vốn từ'],
    en_skills: ['Voracious reader', 'Creativity', 'Life observation', 'Persistence', 'Vocabulary'],
    vi_path: 'Đọc 100+ sách → viết blog/Wattpad → tự xuất bản → NXB lớn',
    en_path: 'Read 100+ books → blog/Wattpad → self-publish → major publisher',
    vn_context: 'Nguyễn Nhật Ánh bán hơn 10 triệu cuốn — phim chuyển thể đoạt giải',
    vn_example: 'Nguyễn Nhật Ánh, Bảo Ninh, Trần Đăng Khoa',
    vn_salary: 'Bất định (5tr-tỷ/tác phẩm)',
  },
  { id: 'interior', type: 'A', emoji: '🛋️', min_age: 11,
    vi_name: 'KTS nội thất', en_name: 'Interior Designer',
    vi_desc: 'Thiết kế không gian sống — phòng ngủ mơ ước, văn phòng đẹp',
    en_desc: 'Design living spaces — dream bedrooms, beautiful offices',
    vi_skills: ['Vẽ', 'Thẩm mỹ', '3D modeling', 'Quản lý dự án', 'Giao tiếp'],
    en_skills: ['Drawing', 'Aesthetics', '3D modeling', 'Project management', 'Communication'],
    vi_path: 'Trang trí phòng riêng → portfolio → ĐH Kiến trúc/Mỹ thuật',
    en_path: 'Decorate own room → portfolio → architecture/design school',
    vn_context: 'Boom condo cao cấp + biệt thự — Vingroup, Sun Group cần KTS nội thất',
    vn_salary: '15-80tr/tháng',
  },
  { id: 'photographer', type: 'A', emoji: '📸', min_age: 10,
    vi_name: 'Nhiếp ảnh gia', en_name: 'Photographer',
    vi_desc: 'Bắt khoảnh khắc đẹp — đám cưới, sản phẩm, tin tức, thời trang',
    en_desc: 'Capture moments — weddings, products, news, fashion',
    vi_skills: ['Mắt thẩm mỹ', 'Kỹ thuật máy', 'Edit Lightroom', 'Kiên nhẫn', 'Giao tiếp'],
    en_skills: ['Aesthetic eye', 'Camera tech', 'Lightroom editing', 'Patience', 'Communication'],
    vi_path: 'Chụp điện thoại → DSLR → Instagram portfolio → studio chuyên',
    en_path: 'Phone photos → DSLR → Instagram portfolio → professional studio',
    vn_context: 'Wedding/product/Instagram VN cần nhiếp ảnh gia trẻ giá phải chăng',
    vn_salary: '10-100tr/tháng',
  },
  { id: 'choreographer', type: 'A', emoji: '💃', min_age: 9,
    vi_name: 'Biên đạo múa', en_name: 'Choreographer',
    vi_desc: 'Tạo điệu nhảy cho show, MV, sân khấu — nghệ thuật chuyển động',
    en_desc: 'Create dances for shows, MVs, theatre — art of movement',
    vi_skills: ['Nhảy', 'Cảm thụ âm nhạc', 'Sáng tạo', 'Lãnh đạo', 'Sức khoẻ'],
    en_skills: ['Dance', 'Musicality', 'Creativity', 'Leadership', 'Fitness'],
    vi_path: 'Học nhảy hiphop/contemp → studio → ĐH Múa VN',
    en_path: 'Hip-hop/contemporary → studio → dance university',
    vn_context: 'VPop MV cần biên đạo — chương trình Street Dance VN, Vũ điệu vàng',
    vn_salary: '15-80tr/show',
  },
  { id: 'game_designer', type: 'A', emoji: '🎮', min_age: 10,
    vi_name: 'Game Designer', en_name: 'Game Designer',
    vi_desc: 'Thiết kế game — gameplay, level, nhân vật, kinh tế trong game',
    en_desc: 'Design games — gameplay, levels, characters, in-game economy',
    vi_skills: ['Sáng tạo', 'Logic', 'Storytelling', 'Phân tích người chơi', 'Tiếng Anh'],
    en_skills: ['Creativity', 'Logic', 'Storytelling', 'Player analytics', 'English'],
    vi_path: 'Chơi nhiều thể loại → mod game → Roblox/Scratch → studio game',
    en_path: 'Play many genres → mod games → Roblox/Scratch → game studio',
    vn_context: 'VNG, Garena, Sky Mavis (Axie Infinity) tuyển game designer',
    vn_example: 'Sky Mavis (founder Trung Nguyễn) — Axie Infinity tỷ USD',
    vn_salary: '20-150tr/tháng',
  },
  { id: 'content_creator', type: 'A', emoji: '📹', min_age: 8,
    vi_name: 'Nhà sáng tạo nội dung', en_name: 'Content Creator',
    vi_desc: 'Làm YouTube, TikTok, Instagram — kể chuyện qua video, hình',
    en_desc: 'Make YouTube, TikTok, Instagram — tell stories via video/images',
    vi_skills: ['Sáng tạo', 'Edit video', 'Kết nối khán giả', 'Đều đặn', 'Phân tích trend'],
    en_skills: ['Creativity', 'Video editing', 'Audience connection', 'Consistency', 'Trend analysis'],
    vi_path: 'Quay video → CapCut edit → upload đều → 1000 sub → monetize',
    en_path: 'Film → CapCut edit → consistent upload → 1000 subs → monetize',
    vn_context: 'Top creator VN: Khoa Pug, Bà Tân Vlog, Quỳnh Trần JP — triệu USD/năm',
    vn_example: 'Quỳnh Trần JP (5M+ subs), Khoa Pug, NTN Vlogs',
    vn_salary: 'Bất định (0-tỷ)',
  },

  // ============== S — Social (10) ==============
  { id: 'teacher', type: 'S', emoji: '👨‍🏫', min_age: 8,
    vi_name: 'Giáo viên', en_name: 'Teacher',
    vi_desc: 'Dạy học sinh — nghề định hình thế hệ tương lai',
    en_desc: 'Teach students — shape the next generation',
    vi_skills: ['Kiên nhẫn', 'Truyền cảm hứng', 'Kiến thức môn', 'Giao tiếp', 'Sáng tạo'],
    en_skills: ['Patience', 'Inspiration', 'Subject mastery', 'Communication', 'Creativity'],
    vi_path: 'Giúp em học bài → CLB tutor → ĐH Sư phạm',
    en_path: 'Tutor siblings → tutor club → teacher college',
    vn_context: 'Giáo viên Anh ngữ + STEM lương cao tại trường tư + dạy thêm',
    vn_salary: '10-80tr/tháng (giáo viên tiếng Anh)',
  },
  { id: 'pediatrician', type: 'S', emoji: '👶', min_age: 11,
    vi_name: 'Bác sĩ nhi khoa', en_name: 'Pediatrician',
    vi_desc: 'Bác sĩ chuyên cho trẻ em — yêu trẻ + giỏi y khoa',
    en_desc: 'Doctor for kids — love children + medical excellence',
    vi_skills: ['Y khoa', 'Yêu trẻ', 'Kiên nhẫn', 'Giao tiếp với phụ huynh', 'Bình tĩnh'],
    en_skills: ['Medicine', 'Love for kids', 'Patience', 'Parent communication', 'Calmness'],
    vi_path: 'Như bác sĩ + chuyên ngành nhi sau 6 năm Y',
    en_path: 'Like doctor + pediatric specialty after 6 years',
    vn_context: 'Bệnh viện Nhi Đồng 1, 2, TƯ luôn quá tải — cần bác sĩ nhi gấp',
    vn_salary: '20-150tr/tháng',
  },
  { id: 'social_worker', type: 'S', emoji: '🤝', min_age: 12,
    vi_name: 'Công tác xã hội', en_name: 'Social Worker',
    vi_desc: 'Giúp người yếu thế — trẻ mồ côi, người vô gia cư, nạn nhân',
    en_desc: 'Help vulnerable people — orphans, homeless, victims',
    vi_skills: ['Đồng cảm', 'Bền bỉ', 'Tổ chức', 'Pháp lý cơ bản', 'Networking'],
    en_skills: ['Empathy', 'Endurance', 'Organization', 'Basic law', 'Networking'],
    vi_path: 'Tình nguyện → ĐH KHXH&NV ngành CTXH',
    en_path: 'Volunteer → social work degree',
    vn_context: 'NGOs VN + Save the Children + UNICEF tuyển CTV',
    vn_salary: '8-30tr/tháng',
  },
  { id: 'nurse', type: 'S', emoji: '💉', min_age: 11,
    vi_name: 'Y tá / Điều dưỡng', en_name: 'Nurse',
    vi_desc: 'Chăm sóc bệnh nhân hằng ngày — quan trọng không kém bác sĩ',
    en_desc: 'Daily patient care — as important as doctors',
    vi_skills: ['Y học cơ bản', 'Chăm sóc', 'Sức khoẻ', 'Bình tĩnh', 'Đồng cảm'],
    en_skills: ['Basic medicine', 'Caring', 'Stamina', 'Calmness', 'Empathy'],
    vi_path: 'ĐH/CĐ Điều dưỡng → bệnh viện hoặc xuất khẩu lao động Nhật/Đức',
    en_path: 'Nursing college → hospital or export to Japan/Germany',
    vn_context: 'Y tá VN xuất khẩu Nhật/Đức lương 50-100tr/tháng + visa',
    vn_salary: '10-100tr/tháng (xuất khẩu)',
  },
  { id: 'tour_guide', type: 'S', emoji: '🗺️', min_age: 12,
    vi_name: 'Hướng dẫn viên du lịch', en_name: 'Tour Guide',
    vi_desc: 'Đưa khách khám phá VN/thế giới — kể chuyện văn hoá lịch sử',
    en_desc: 'Take tourists to discover VN/world — tell culture/history',
    vi_skills: ['Tiếng Anh+', 'Lịch sử', 'Giao tiếp', 'Sức khoẻ', 'Hài hước'],
    en_skills: ['English+', 'History', 'Communication', 'Stamina', 'Humor'],
    vi_path: 'Học nhiều ngoại ngữ → ĐH Du lịch HCM → chứng chỉ HDV',
    en_path: 'Multiple languages → tourism university → guide certs',
    vn_context: '18 triệu khách quốc tế/năm — cần HDV tiếng Hàn, Nhật, Trung gấp',
    vn_salary: '15-80tr/tháng + tip',
  },
  { id: 'therapist', type: 'S', emoji: '💆', min_age: 12,
    vi_name: 'Nhà trị liệu', en_name: 'Therapist',
    vi_desc: 'Trị liệu tâm lý, vật lý, ngôn ngữ — phục hồi sức khoẻ',
    en_desc: 'Psychology, physical, speech therapy — restore health',
    vi_skills: ['Đồng cảm', 'Y khoa', 'Kiên nhẫn', 'Giao tiếp', 'Học liên tục'],
    en_skills: ['Empathy', 'Medical knowledge', 'Patience', 'Communication', 'Lifelong learning'],
    vi_path: 'ĐH Y/Tâm lý → chuyên ngành trị liệu → chứng chỉ quốc tế',
    en_path: 'Medical/psych university → therapy specialty → international certs',
    vn_context: 'Nhu cầu trị liệu trẻ tự kỷ + người cao tuổi tăng nhanh',
    vn_salary: '15-100tr/tháng',
  },
  { id: 'volunteer', type: 'S', emoji: '🌍', min_age: 13,
    vi_name: 'Tình nguyện viên quốc tế', en_name: 'International Volunteer',
    vi_desc: 'Tham gia UN, NGOs lớn — giúp đỡ thế giới + đi du lịch',
    en_desc: 'Join UN, big NGOs — help the world + travel',
    vi_skills: ['Tiếng Anh', 'Đa văn hoá', 'Sức bền', 'Lãnh đạo', 'Kỹ năng cụ thể'],
    en_skills: ['English', 'Multicultural', 'Endurance', 'Leadership', 'Specific skills'],
    vi_path: 'IELTS 7+ → tham gia AIESEC → UNV/Peace Corps',
    en_path: 'IELTS 7+ → AIESEC → UN Volunteers/Peace Corps',
    vn_context: 'AIESEC VN active — gửi hàng nghìn TNV ra quốc tế mỗi năm',
    vn_salary: '15-50tr/tháng + chi phí',
  },
  { id: 'life_coach', type: 'S', emoji: '🎯', min_age: 14,
    vi_name: 'Huấn luyện viên đời sống', en_name: 'Life Coach',
    vi_desc: 'Giúp người khác đạt mục tiêu — sự nghiệp, sức khoẻ, hạnh phúc',
    en_desc: 'Help others reach goals — career, health, happiness',
    vi_skills: ['Lắng nghe', 'Hỏi tốt', 'Truyền cảm hứng', 'Nội dung', 'Marketing bản thân'],
    en_skills: ['Listening', 'Good questioning', 'Inspiration', 'Content', 'Personal branding'],
    vi_path: 'Tự phát triển bản thân → khoá ICF → coaching practice',
    en_path: 'Self-development → ICF certification → coaching practice',
    vn_context: 'Coach VN bùng nổ — Quách Tuấn Khanh, Lê Thẩm Dương lãnh đạo',
    vn_salary: '20-300tr/tháng',
  },
  { id: 'diplomat', type: 'S', emoji: '🌐', min_age: 14,
    vi_name: 'Nhà ngoại giao', en_name: 'Diplomat',
    vi_desc: 'Đại diện VN ở nước ngoài — đại sứ quán, hợp tác quốc tế',
    en_desc: 'Represent Vietnam abroad — embassies, international cooperation',
    vi_skills: ['Tiếng Anh+', 'Lịch sử', 'Chính trị', 'Etiquette', 'Đa ngôn ngữ'],
    en_skills: ['English+', 'History', 'Politics', 'Etiquette', 'Multilingual'],
    vi_path: 'IELTS 8+ → Học viện Ngoại giao HN → thi tuyển Bộ Ngoại giao',
    en_path: 'IELTS 8+ → Diplomatic Academy → MOFA exam',
    vn_context: 'Bộ Ngoại giao tuyển hằng năm — học bổng đi du học miễn phí',
    vn_salary: '15-100tr + phụ cấp đi nước ngoài',
  },
  { id: 'mc', type: 'S', emoji: '🎤', min_age: 11,
    vi_name: 'MC / Người dẫn chương trình', en_name: 'TV Host / MC',
    vi_desc: 'Dẫn chương trình truyền hình, sự kiện, livestream',
    en_desc: 'Host TV shows, events, livestreams',
    vi_skills: ['Tự tin nói', 'Giọng tốt', 'Phản xạ nhanh', 'Tiếng Anh', 'Diện mạo'],
    en_skills: ['Confident speaking', 'Good voice', 'Quick reflexes', 'English', 'Presentation'],
    vi_path: 'Tham gia kịch trường → MC sự kiện trường → audition VTV',
    en_path: 'School drama → school MC → TV station audition',
    vn_context: 'VTV/HTV/VTC tuyển MC trẻ + livestream commerce TikTok bùng nổ',
    vn_example: 'Quyền Linh, MC Trác Thuý Miêu',
    vn_salary: '15-200tr/show',
  },

  // ============== E — Enterprising (10) ==============
  { id: 'entrepreneur', type: 'E', emoji: '🚀', min_age: 10,
    vi_name: 'Doanh nhân', en_name: 'Entrepreneur',
    vi_desc: 'Lập startup, mở công ty — biến ý tưởng thành kinh doanh',
    en_desc: 'Found startups, build companies — turn ideas into business',
    vi_skills: ['Lãnh đạo', 'Thuyết phục', 'Sáng tạo', 'Chấp nhận rủi ro', 'Networking'],
    en_skills: ['Leadership', 'Persuasion', 'Creativity', 'Risk taking', 'Networking'],
    vi_path: 'Bán đồ ăn vặt ở trường → kinh doanh online → khởi nghiệp thật',
    en_path: 'Sell snacks at school → online business → real startup',
    vn_context: 'VN có shark tank → nhiều startup unicorn: VNG, VNPay, MoMo, Sky Mavis',
    vn_example: 'Phạm Nhật Vượng (VinGroup), Trung Nguyễn (Sky Mavis)',
    vn_salary: 'Bất định (0 - tỷ USD)',
  },
  { id: 'lawyer', type: 'E', emoji: '⚖️', min_age: 12,
    vi_name: 'Luật sư', en_name: 'Lawyer',
    vi_desc: 'Bảo vệ khách hàng tại toà — luật doanh nghiệp, gia đình, hình sự',
    en_desc: 'Defend clients in court — corporate, family, criminal law',
    vi_skills: ['Logic', 'Diễn thuyết', 'Đọc nhiều', 'Trí nhớ', 'Tiếng Anh (cho intl law)'],
    en_skills: ['Logic', 'Speaking', 'Voracious reading', 'Memory', 'English (for intl)'],
    vi_path: 'Tham gia debate → ĐH Luật HCM/HN → thi luật sư + tập sự',
    en_path: 'Debate club → law university → bar exam + apprenticeship',
    vn_context: 'Top luật sư VN doanh nghiệp lương 100-500tr — mảng M&A, IP',
    vn_salary: '15-500tr/tháng',
  },
  { id: 'ceo', type: 'E', emoji: '💼', min_age: 14,
    vi_name: 'Tổng giám đốc (CEO)', en_name: 'CEO',
    vi_desc: 'Lãnh đạo công ty lớn — quyết định chiến lược + quản lý nghìn người',
    en_desc: 'Lead big company — strategic decisions + manage thousands',
    vi_skills: ['Lãnh đạo', 'Tài chính', 'Chiến lược', 'Quyết đoán', 'Kiên cường'],
    en_skills: ['Leadership', 'Finance', 'Strategy', 'Decisiveness', 'Resilience'],
    vi_path: 'Lãnh đạo lớp/CLB → MBA top → leo từ analyst → manager → CEO',
    en_path: 'Class/club leader → top MBA → analyst → manager → CEO',
    vn_context: 'CEO doanh nghiệp lớn VN: Vingroup, Vinamilk, FPT lương tỷ đồng/năm',
    vn_example: 'Mai Kiều Liên (Vinamilk), Nguyễn Thị Phương Thảo (VietJet)',
    vn_salary: '500tr - 50 tỷ/năm',
  },
  { id: 'journalist', type: 'E', emoji: '📰', min_age: 11,
    vi_name: 'Nhà báo', en_name: 'Journalist',
    vi_desc: 'Đưa tin sự thật — báo, TV, online, podcast',
    en_desc: 'Report the truth — newspapers, TV, online, podcasts',
    vi_skills: ['Viết tốt', 'Đặt câu hỏi', 'Tò mò', 'Liều lĩnh', 'Tiếng Anh'],
    en_skills: ['Writing', 'Questioning', 'Curiosity', 'Boldness', 'English'],
    vi_path: 'Viết blog/bài → tham gia báo trường → ĐH Báo chí',
    en_path: 'Blog → school newspaper → journalism university',
    vn_context: 'VnExpress, Tuổi Trẻ, Vietcetera — tuyển nhà báo trẻ + freelance',
    vn_salary: '10-50tr/tháng',
  },
  { id: 'politician', type: 'E', emoji: '🏛️', min_age: 14,
    vi_name: 'Chính trị gia', en_name: 'Politician',
    vi_desc: 'Phục vụ đất nước — đại biểu QH, lãnh đạo địa phương, ngoại giao',
    en_desc: 'Serve the country — parliament, local leadership, diplomacy',
    vi_skills: ['Lãnh đạo', 'Diễn thuyết', 'Networking', 'Lịch sử', 'Tự kỷ luật'],
    en_skills: ['Leadership', 'Public speaking', 'Networking', 'History', 'Self-discipline'],
    vi_path: 'Lãnh đạo Đoàn → Đảng viên → ĐH Luật/CTQG → sự nghiệp chính trị',
    en_path: 'Youth Union leader → party member → law/political university → career',
    vn_context: 'Đảng viên trẻ + thi tuyển công chức → lộ trình rõ ràng',
    vn_salary: 'Theo chức vụ (15-100tr)',
  },
  { id: 'manager', type: 'E', emoji: '📊', min_age: 13,
    vi_name: 'Nhà quản lý', en_name: 'Manager',
    vi_desc: 'Quản lý team trong công ty — đảm bảo dự án thành công',
    en_desc: 'Manage teams in companies — ensure projects succeed',
    vi_skills: ['Lãnh đạo', 'Tổ chức', 'Giao tiếp', 'Giải quyết xung đột', 'Tin học'],
    en_skills: ['Leadership', 'Organization', 'Communication', 'Conflict resolution', 'Tech'],
    vi_path: 'Lãnh đạo CLB → ĐH Kinh tế/Quản trị → analyst → manager',
    en_path: 'Club leader → business university → analyst → manager',
    vn_context: 'Mọi công ty đều cần manager — lương 25-100tr cho mid-level',
    vn_salary: '25-200tr/tháng',
  },
  { id: 'investor', type: 'E', emoji: '💰', min_age: 13,
    vi_name: 'Nhà đầu tư', en_name: 'Investor',
    vi_desc: 'Đầu tư cổ phiếu, BĐS, startup — tiền đẻ ra tiền',
    en_desc: 'Invest in stocks, real estate, startups — money makes money',
    vi_skills: ['Tài chính', 'Phân tích', 'Kiên nhẫn', 'Quản lý rủi ro', 'Tiếng Anh'],
    en_skills: ['Finance', 'Analysis', 'Patience', 'Risk management', 'English'],
    vi_path: 'Hiểu lãi kép → demo account chứng khoán → ĐH Kinh tế/Tài chính',
    en_path: 'Compound interest → stock demo → finance university',
    vn_context: 'Chứng khoán VN tăng trưởng — VNINDEX 1500+ điểm tiềm năng',
    vn_example: 'Phạm Nhật Vượng đầu tư đa ngành tỷ USD',
    vn_salary: 'Bất định (0 - tỷ USD)',
  },
  { id: 'startup_founder', type: 'E', emoji: '🦄', min_age: 12,
    vi_name: 'Nhà sáng lập startup', en_name: 'Startup Founder',
    vi_desc: 'Tạo công ty công nghệ mới — tham vọng unicorn',
    en_desc: 'Create new tech companies — unicorn ambitions',
    vi_skills: ['Sáng tạo', 'Coding cơ bản', 'Marketing', 'Pitch', 'Liều'],
    en_skills: ['Creativity', 'Basic coding', 'Marketing', 'Pitching', 'Risk-taking'],
    vi_path: 'Side project → MVP → tham gia hackathon → tìm cofounder → gọi vốn',
    en_path: 'Side project → MVP → hackathon → cofounder → fundraise',
    vn_context: 'Startup VN nhận đầu tư từ Y Combinator, 500 Startups — Cốc Cốc, MoMo',
    vn_example: 'Trung Nguyễn (Sky Mavis), Founders Tiki',
    vn_salary: '0 - 1 tỷ USD (long shot)',
  },
  { id: 'sales_manager', type: 'E', emoji: '💼', min_age: 13,
    vi_name: 'Quản lý bán hàng', en_name: 'Sales Manager',
    vi_desc: 'Lãnh đạo team sales — chốt deal lớn, đạt KPI',
    en_desc: 'Lead sales teams — close big deals, hit KPIs',
    vi_skills: ['Thuyết phục', 'Số liệu', 'Tâm lý khách', 'Kiên trì', 'Lãnh đạo'],
    en_skills: ['Persuasion', 'Numbers', 'Customer psychology', 'Persistence', 'Leadership'],
    vi_path: 'Bán hàng học sinh → sales rep → leader → manager',
    en_path: 'Student sales → sales rep → leader → manager',
    vn_context: 'BĐS, ô tô, B2B SaaS VN trả commission cao 100-500tr/tháng',
    vn_salary: '20-500tr/tháng',
  },
  { id: 'consultant', type: 'E', emoji: '🎯', min_age: 14,
    vi_name: 'Nhà tư vấn quản lý', en_name: 'Management Consultant',
    vi_desc: 'Tư vấn chiến lược cho công ty lớn — McKinsey, BCG, Bain',
    en_desc: 'Strategic advice to big companies — McKinsey, BCG, Bain',
    vi_skills: ['Phân tích', 'Tiếng Anh+', 'Excel/PPT', 'Giao tiếp', 'Học nhanh'],
    en_skills: ['Analysis', 'English+', 'Excel/PPT', 'Communication', 'Fast learning'],
    vi_path: 'Top student + IELTS 8 → top university → MBB internship',
    en_path: 'Top student + IELTS 8 → top uni → MBB internship',
    vn_context: 'McKinsey/BCG VN tuyển — lương khởi điểm 80-150tr/tháng',
    vn_salary: '80-500tr/tháng',
  },

  // ============== C — Conventional (10) ==============
  { id: 'accountant', type: 'C', emoji: '🧮', min_age: 12,
    vi_name: 'Kế toán', en_name: 'Accountant',
    vi_desc: 'Quản lý sổ sách công ty — đảm bảo mọi đồng tiền đúng chỗ',
    en_desc: 'Manage company books — ensure every dollar is in place',
    vi_skills: ['Toán', 'Cẩn thận', 'Excel', 'Quy chuẩn', 'Trí nhớ số liệu'],
    en_skills: ['Math', 'Carefulness', 'Excel', 'Standards', 'Number memory'],
    vi_path: 'Giỏi Toán → ĐH Kinh tế/Tài chính → CFA/ACCA',
    en_path: 'Strong Math → economics/finance university → CFA/ACCA',
    vn_context: 'Big4 KPMG/EY/Deloitte/PwC tuyển hàng năm tại VN',
    vn_salary: '12-200tr/tháng (CFO)',
  },
  { id: 'banker', type: 'C', emoji: '🏦', min_age: 13,
    vi_name: 'Nhân viên ngân hàng', en_name: 'Banker',
    vi_desc: 'Làm việc trong ngân hàng — cho vay, đầu tư, quản lý tài sản',
    en_desc: 'Work in banks — lending, investment, wealth management',
    vi_skills: ['Tài chính', 'Cẩn thận', 'Giao tiếp', 'Tiếng Anh', 'Đáng tin cậy'],
    en_skills: ['Finance', 'Carefulness', 'Communication', 'English', 'Trustworthy'],
    vi_path: 'ĐH Tài chính/Ngân hàng → Vietcombank/BIDV tuyển dụng',
    en_path: 'Finance university → big bank recruitment',
    vn_context: 'Vietcombank, BIDV, Techcombank — top tuyển sinh viên giỏi',
    vn_salary: '15-200tr/tháng',
  },
  { id: 'librarian', type: 'C', emoji: '📚', min_age: 9,
    vi_name: 'Thủ thư / Nhà thư viện học', en_name: 'Librarian',
    vi_desc: 'Quản lý thư viện — phân loại sách, giúp người tìm tài liệu',
    en_desc: 'Manage libraries — categorize books, help researchers',
    vi_skills: ['Tổ chức', 'Đọc nhiều', 'Cẩn thận', 'Giúp đỡ', 'Tin học'],
    en_skills: ['Organization', 'Reading', 'Carefulness', 'Helpfulness', 'IT'],
    vi_path: 'Đọc 100+ sách → ĐH Văn hoá ngành thư viện',
    en_path: 'Read 100+ books → cultural university library science',
    vn_context: 'Thư viện trường ĐH lớn cần — lương ổn định, ít stress',
    vn_salary: '8-25tr/tháng',
  },
  { id: 'sysadmin', type: 'C', emoji: '🖥️', min_age: 12,
    vi_name: 'Quản trị hệ thống', en_name: 'System Administrator',
    vi_desc: 'Đảm bảo hệ thống IT công ty hoạt động 24/7',
    en_desc: 'Keep company IT systems running 24/7',
    vi_skills: ['Linux', 'Networking', 'Bảo mật', 'Cẩn thận', 'Tiếng Anh kỹ thuật'],
    en_skills: ['Linux', 'Networking', 'Security', 'Carefulness', 'Technical English'],
    vi_path: 'Tự học Linux → ĐH CNTT → chứng chỉ AWS/Azure',
    en_path: 'Self-learn Linux → IT university → AWS/Azure certs',
    vn_context: 'Mọi công ty cần sysadmin — DevOps lương 30-100tr/tháng',
    vn_salary: '20-100tr/tháng',
  },
  { id: 'auditor', type: 'C', emoji: '✅', min_age: 13,
    vi_name: 'Kiểm toán viên', en_name: 'Auditor',
    vi_desc: 'Kiểm tra sổ sách công ty xem có gian lận không',
    en_desc: 'Audit company books for fraud',
    vi_skills: ['Cẩn thận', 'Phân tích', 'Tiếng Anh', 'Đạo đức', 'Tỉ mỉ'],
    en_skills: ['Carefulness', 'Analysis', 'English', 'Ethics', 'Detail-oriented'],
    vi_path: 'Như kế toán + CPA/ACCA → Big4 audit',
    en_path: 'Like accountant + CPA/ACCA → Big4 audit',
    vn_context: 'Big4 + audit firms VN tuyển fresh graduate cao điểm',
    vn_salary: '15-150tr/tháng',
  },
  { id: 'logistics', type: 'C', emoji: '📦', min_age: 12,
    vi_name: 'Logistics & chuỗi cung ứng', en_name: 'Logistics & Supply Chain',
    vi_desc: 'Tổ chức vận chuyển hàng hoá toàn cầu — Amazon, Shopee',
    en_desc: 'Organize global shipping — Amazon, Shopee',
    vi_skills: ['Tổ chức', 'Phân tích', 'Tiếng Anh', 'Excel', 'Giải quyết vấn đề'],
    en_skills: ['Organization', 'Analysis', 'English', 'Excel', 'Problem solving'],
    vi_path: 'ĐH Ngoại thương/Hàng hải ngành logistics',
    en_path: 'International trade/maritime university — logistics',
    vn_context: 'VN trở thành trung tâm logistics ASEAN — Vinalines, Tanship',
    vn_salary: '15-100tr/tháng',
  },
  { id: 'secretary', type: 'C', emoji: '📝', min_age: 13,
    vi_name: 'Thư ký / Trợ lý điều hành', en_name: 'Executive Assistant',
    vi_desc: 'Trợ lý cho CEO — sắp xếp lịch, email, hỗ trợ ra quyết định',
    en_desc: 'Assist CEOs — schedule, emails, decision support',
    vi_skills: ['Tổ chức', 'Giao tiếp', 'Tiếng Anh', 'Bí mật', 'Đa nhiệm'],
    en_skills: ['Organization', 'Communication', 'English', 'Discretion', 'Multitasking'],
    vi_path: 'ĐH Kinh tế/Quản trị → vị trí EA → senior EA',
    en_path: 'Business university → EA role → senior EA',
    vn_context: 'Top EA VN cho corporate lương 30-80tr + thưởng',
    vn_salary: '15-100tr/tháng',
  },
  { id: 'data_analyst', type: 'C', emoji: '📈', min_age: 11,
    vi_name: 'Chuyên viên phân tích dữ liệu', en_name: 'Data Analyst',
    vi_desc: 'Biến số liệu thành insight — Excel, SQL, Python, Tableau',
    en_desc: 'Turn numbers into insights — Excel, SQL, Python, Tableau',
    vi_skills: ['Toán/Thống kê', 'SQL', 'Excel', 'Tiếng Anh', 'Storytelling'],
    en_skills: ['Math/Stats', 'SQL', 'Excel', 'English', 'Storytelling'],
    vi_path: 'Excel + Power BI → Python pandas → Kaggle → ĐH/bootcamp',
    en_path: 'Excel + Power BI → Python pandas → Kaggle → uni/bootcamp',
    vn_context: 'Mọi công ty VN đều cần data analyst — junior 15-25tr',
    vn_salary: '15-100tr/tháng',
  },
  { id: 'backend_dev', type: 'C', emoji: '🛠️', min_age: 11,
    vi_name: 'Lập trình viên backend', en_name: 'Backend Developer',
    vi_desc: 'Build server, database, API — phía sau mọi app',
    en_desc: 'Build servers, databases, APIs — behind every app',
    vi_skills: ['Logic mạnh', 'Python/Java/Go', 'SQL', 'Networking', 'Tiếng Anh'],
    en_skills: ['Strong logic', 'Python/Java/Go', 'SQL', 'Networking', 'English'],
    vi_path: 'Python cơ bản → web framework → freelance → công ty',
    en_path: 'Python basics → web framework → freelance → company',
    vn_context: 'Backend VN lương cao — Senior 50-150tr, FAANG remote 200-500tr',
    vn_salary: '20-500tr/tháng',
  },
  { id: 'pm', type: 'C', emoji: '🗂️', min_age: 13,
    vi_name: 'Project Manager', en_name: 'Project Manager',
    vi_desc: 'Quản lý dự án — đảm bảo đúng deadline, ngân sách, chất lượng',
    en_desc: 'Manage projects — on-time, on-budget, quality',
    vi_skills: ['Tổ chức', 'Giao tiếp', 'Lãnh đạo', 'Phân tích', 'Tin học PM tools'],
    en_skills: ['Organization', 'Communication', 'Leadership', 'Analysis', 'PM tools'],
    vi_path: 'Lãnh đạo CLB → fresh ĐH → coordinator → PM → senior PM',
    en_path: 'Club leader → fresh uni → coordinator → PM → senior PM',
    vn_context: 'IT/BĐS/Construction VN cần PM — chứng chỉ PMP cộng điểm',
    vn_salary: '25-200tr/tháng',
  },
];

export const CAREER_PROJECTS = [
  // "Day in the life" mini-projects — 30 minutes for kids to try
  { career_type: 'R', vi: 'Tự lắp ráp món đồ chơi cũ + ghi chú quá trình (30 phút)', en: 'Reassemble an old toy + take notes of the process (30 min)' },
  { career_type: 'R', vi: 'Vẽ bản thiết kế nhà mơ ước với kích thước thật (30 phút)', en: 'Draw blueprint of dream house with real measurements (30 min)' },
  { career_type: 'R', vi: 'Nấu một món ăn theo công thức + chấm điểm bản thân', en: 'Cook a meal following a recipe + grade yourself' },
  { career_type: 'I', vi: 'Tìm hiểu một câu hỏi "tại sao" qua 5 nguồn khác nhau', en: 'Research one "why" question across 5 different sources' },
  { career_type: 'I', vi: 'Làm 1 thí nghiệm khoa học tại nhà + ghi lab notebook', en: 'Do 1 home science experiment + write lab notebook' },
  { career_type: 'I', vi: 'Đọc 1 chương sách Toán/Lý/Sinh vượt cấp + giải bài', en: 'Read advanced Math/Phy/Bio chapter + solve problems' },
  { career_type: 'A', vi: 'Vẽ 1 nhân vật mới + viết câu chuyện 200 từ về nhân vật đó', en: 'Draw a new character + write a 200-word story about them' },
  { career_type: 'A', vi: 'Tự edit 1 video TikTok 15-30 giây với chuyển cảnh + nhạc', en: 'Self-edit a 15-30s TikTok with transitions + music' },
  { career_type: 'A', vi: 'Sáng tác 1 bài thơ/bài hát/đoạn nhạc về gia đình', en: 'Compose 1 poem/song/melody about your family' },
  { career_type: 'S', vi: 'Dạy em hoặc bạn 1 kỹ năng con biết + ghi nhận xét họ học thế nào', en: 'Teach a sibling/friend a skill + note how they learn' },
  { career_type: 'S', vi: 'Viết thư động viên 3 người bạn/người thân khác nhau', en: 'Write encouraging letters to 3 different friends/family' },
  { career_type: 'S', vi: 'Tổ chức hoạt động nhóm 5 bạn + làm leader 30 phút', en: 'Organize a 5-friend group activity + lead for 30 min' },
  { career_type: 'E', vi: 'Pitch ý tưởng kinh doanh nhỏ trong 3 phút (record video)', en: 'Pitch a small business idea in 3 min (record video)' },
  { career_type: 'E', vi: 'Tổ chức bán đồ ăn/thủ công + theo dõi lãi lỗ trên giấy', en: 'Organize food/craft sale + track P&L on paper' },
  { career_type: 'E', vi: 'Viết "kế hoạch 1 năm" cho mục tiêu lớn của con', en: 'Write a "1-year plan" for your big personal goal' },
  { career_type: 'C', vi: 'Sắp xếp lại tủ quần áo theo hệ thống mới + tài liệu hoá', en: 'Reorganize wardrobe with new system + document it' },
  { career_type: 'C', vi: 'Làm spreadsheet ngân sách tiêu vặt 1 tháng có biểu đồ', en: 'Make pocket money budget spreadsheet for 1 month with charts' },
  { career_type: 'C', vi: 'Tạo bullet journal 1 tuần với habit tracker + reflection', en: 'Create 1-week bullet journal with habit tracker + reflection' },
];

export function getCareersByType(type: RiasecType): Career[] {
  return CAREERS.filter(c => c.type === type);
}

export function getCareerOfDay(): Career {
  const dayOfYear = Math.floor((Date.now() - new Date(new Date().getFullYear(), 0, 0).getTime()) / 86400000);
  return CAREERS[dayOfYear % CAREERS.length];
}

export function getProjectForType(type: RiasecType): typeof CAREER_PROJECTS[0] {
  const projects = CAREER_PROJECTS.filter(p => p.career_type === type);
  return projects[Math.floor(Math.random() * projects.length)];
}
